// ===== Cambridge Checkpoint content (Primary Stage 6 + Lower Secondary Stage 9) =====
// Maths + Science, with theory notes, written questions, and past-paper style questions.

import type { Topic, Question } from "./quizData";

export type CheckpointStage = "stage6" | "stage9";
export type CheckpointSubject = "maths" | "science";

export const CHECKPOINT_STAGES: { id: CheckpointStage; name: string; shortName: string; year: string; description: string; color: string }[] = [
  { id: "stage6", name: "Primary Checkpoint", shortName: "Stage 6", year: "Year 6", description: "Cambridge Primary Checkpoint — the end of primary maths and science. Builds exam confidence with past-paper style questions.", color: "#f5c842" },
  { id: "stage9", name: "Lower Secondary Checkpoint", shortName: "Stage 9", year: "Year 9", description: "Cambridge Lower Secondary Checkpoint — prepares you for IGCSE with harder maths and science, including past-paper practice.", color: "#22d3ee" },
];

const pp = (q: Question): Question => ({ ...q, pastPaper: true, cambridge: true });
const w = (q: Question): Question => ({ ...q, type: "written", options: [], answer: 0 });

/* ===================== STAGE 6 MATHS ===================== */
export const CHECKPOINT_STAGE6_MATHS: Topic[] = [
  {
    id: "cp6-number", name: "Number", icon: "Hash", description: "Place value, operations and ordering.",
    defaultTimeLimit: 30,
    theory: "Numbers can be written in different forms: decimals, fractions and percentages.\n\nPlace value tells us the worth of each digit. For example, in 3.75 the 7 is in the tenths place (worth 0.7) and the 5 is in the hundredths place (worth 0.05).\n\nTo convert a fraction to a decimal, divide the top by the bottom: 4/5 = 4 ÷ 5 = 0.8. To find a percentage of a number, multiply: 15% of 240 = 0.15 × 240 = 36.\n\nRounding: look at the digit to the right of your target place. If it's 5 or more, round up. If it's 4 or less, round down.",
    questions: [
      { question: "What is 3.75 × 10?", options: ["3.75", "37.5", "375", "0.375"], answer: 1, explanation: "Multiplying by 10 moves the decimal one place right: 37.5." },
      { question: "Write 4/5 as a decimal.", options: ["0.45", "0.8", "0.5", "0.85"], answer: 1, explanation: "4 ÷ 5 = 0.8." },
      { question: "What is 15% of 240?", options: ["24", "30", "36", "40"], answer: 2, explanation: "0.15 × 240 = 36." },
      { question: "Round 4.782 to 2 decimal places.", options: ["4.78", "4.79", "4.80", "4.7"], answer: 0, explanation: "The third decimal is 2, so round down: 4.78." },
      { question: "Which is largest: 0.6, 0.59, 0.61, 0.5?", options: ["0.6", "0.59", "0.61", "0.5"], answer: 2, explanation: "0.61 is the largest." },
      { question: "What is 7 − (−3)?", options: ["4", "10", "−4", "−10"], answer: 1, explanation: "Subtracting a negative is adding: 7 + 3 = 10." },
      pp({ question: "A shop sells 350g of cheese for £4.20. What is the cost of 100g?", options: ["£1.00", "£1.20", "£1.50", "£1.80"], answer: 1, explanation: "£4.20 ÷ 3.5 = £1.20 per 100g." }),
      pp({ question: "A number is multiplied by itself and then 5 is added. The result is 86. What is the number?", options: ["7", "8", "9", "10"], answer: 2, explanation: "n² + 5 = 86, so n² = 81, n = 9." }),
      pp({ question: "In a test, Aisha scored 18 out of 25. What percentage did she score?", options: ["60%", "68%", "72%", "75%"], answer: 2, explanation: "18/25 = 0.72 = 72%." }),
      pp({ question: "Write 0.04 as a fraction in its simplest form.", options: ["1/25", "1/20", "4/10", "1/4"], answer: 0, explanation: "0.04 = 4/100 = 1/25." }),
      { question: "What is 2.5 × 4?", options: ["8", "10", "6.5", "11"], answer: 1, explanation: "2.5 × 4 = 10." },
      { question: "Round 7.896 to 1 decimal place.", options: ["7.8", "7.9", "8.0", "7.89"], answer: 1, explanation: "Second decimal is 9 (≥5), round up: 7.9." },
      w({ question: "What is 3/4 as a decimal?", acceptAnswers: ["0.75", ".75"], explanation: "3 ÷ 4 = 0.75.", timeLimit: 20 }),
      w({ question: "What is 10% of 650? (just the number)", acceptAnswers: ["65"], explanation: "0.10 × 650 = 65.", timeLimit: 20 }),
      pp(w({ question: "Write 0.6 as a fraction in its simplest form.", acceptAnswers: ["3/5"], explanation: "0.6 = 6/10 = 3/5." })),
    ],
  },
  {
    id: "cp6-geometry", name: "Geometry & Measure", icon: "Shapes", description: "Angles, area, perimeter and volume.",
    defaultTimeLimit: 35,
    theory: "Geometry is about shapes and their properties.\n\nAngles in a triangle always add up to 180°. A straight line is 180°. A full turn is 360°.\n\nArea of a rectangle = length × width. Perimeter = all the sides added together. Volume of a cuboid = length × width × height.\n\nThe area of a triangle = ½ × base × height. The diameter of a circle = 2 × radius.",
    questions: [
      { question: "A triangle has angles 35° and 65°. What is the third angle?", options: ["70°", "80°", "90°", "100°"], answer: 1, explanation: "180 − 35 − 65 = 80°." },
      { question: "A circle has radius 6 cm. What is its diameter?", options: ["3 cm", "6 cm", "12 cm", "36 cm"], answer: 2, explanation: "Diameter = 2 × radius = 12 cm." },
      { question: "A rectangular field is 60 m by 40 m. What is its perimeter?", options: ["100 m", "160 m", "200 m", "2400 m"], answer: 2, explanation: "60 + 40 + 60 + 40 = 200 m." },
      { question: "What is the volume of a cuboid 8 cm × 5 cm × 3 cm?", options: ["16 cm³", "40 cm³", "120 cm³", "160 cm³"], answer: 2, explanation: "8 × 5 × 3 = 120 cm³." },
      { question: "A square has area 81 cm². What is its perimeter?", options: ["18 cm", "36 cm", "40 cm", "81 cm"], answer: 1, explanation: "Side = 9 cm, perimeter = 4 × 9 = 36 cm." },
      pp({ question: "A rectangular swimming pool is 25 m long and 10 m wide. It is filled to a depth of 2 m. What is the volume of water in m³?", options: ["70 m³", "250 m³", "500 m³", "1000 m³"], answer: 2, explanation: "25 × 10 × 2 = 500 m³." }),
      pp({ question: "A triangle has a base of 12 cm and a height of 8 cm. What is its area?", options: ["24 cm²", "48 cm²", "96 cm²", "20 cm²"], answer: 1, explanation: "½ × 12 × 8 = 48 cm²." }),
      pp({ question: "A regular hexagon has interior angles of 120°. What do the 6 interior angles add up to?", options: ["360°", "540°", "720°", "900°"], answer: 2, explanation: "6 × 120° = 720°." }),
      pp({ question: "A tin is a cylinder with radius 4 cm and height 10 cm. Using π ≈ 3.14, what is its volume?", options: ["125.6 cm³", "251.2 cm³", "502.4 cm³", "5024 cm³"], answer: 2, explanation: "π × 4² × 10 = 3.14 × 16 × 10 = 502.4 cm³." }),
      pp({ question: "Two angles on a straight line are x° and 110°. What is x?", options: ["70°", "90°", "110°", "180°"], answer: 0, explanation: "180 − 110 = 70°." }),
      { question: "What is the perimeter of a square with side 7 cm?", options: ["14 cm", "21 cm", "28 cm", "49 cm"], answer: 2, explanation: "4 × 7 = 28 cm." },
      { question: "A rectangle is 9 cm by 6 cm. What is its area?", options: ["15 cm²", "30 cm²", "45 cm²", "54 cm²"], answer: 3, explanation: "9 × 6 = 54 cm²." },
      w({ question: "A triangle has a base of 10 cm and height of 9 cm. What is its area in cm²? (just the number)", acceptAnswers: ["45"], explanation: "½ × 10 × 9 = 45 cm².", timeLimit: 25 }),
      w({ question: "A circle has diameter 20 cm. What is its radius in cm? (just the number)", acceptAnswers: ["10"], explanation: "Radius = diameter ÷ 2 = 10 cm.", timeLimit: 15 }),
      pp(w({ question: "Angles in a triangle total 180°. Two angles are 47° and 68°. What is the third angle in degrees? (just the number)", acceptAnswers: ["65"], explanation: "180 − 47 − 68 = 65°." })),
    ],
  },
  {
    id: "cp6-handling-data", name: "Handling Data", icon: "BarChart3", description: "Mean, median, mode, range and charts.",
    defaultTimeLimit: 30,
    theory: "There are three types of average:\n\nMean = total of all values ÷ number of values.\nMedian = the middle value when the data is in order.\nMode = the value that appears most often.\nRange = highest value − lowest value (this measures how spread out the data is).\n\nBar charts show data with bars of different heights. Pie charts show proportions of a whole. Pictograms use pictures to represent amounts.",
    questions: [
      { question: "Find the mean of 5, 8, 12, 15.", options: ["8", "10", "12", "40"], answer: 1, explanation: "Sum = 40, ÷ 4 = 10." },
      { question: "Find the median of 4, 7, 9, 12, 15.", options: ["7", "9", "12", "15"], answer: 1, explanation: "Middle of 5 sorted numbers = 9." },
      { question: "Find the mode of 3, 5, 5, 5, 8, 9.", options: ["3", "5", "8", "9"], answer: 1, explanation: "5 appears most (3 times)." },
      { question: "Find the range of 12, 4, 18, 7, 25.", options: ["18", "21", "25", "29"], answer: 1, explanation: "Max − min = 25 − 4 = 21." },
      pp({ question: "The table shows goals scored in 10 matches: 2, 1, 3, 0, 2, 4, 2, 1, 3, 2. What is the mode?", options: ["1", "2", "3", "4"], answer: 1, explanation: "2 appears 5 times — the most." }),
      pp({ question: "Five students have masses 42, 38, 45, 41, 44 kg. What is the median mass?", options: ["41 kg", "42 kg", "43 kg", "45 kg"], answer: 1, explanation: "Sorted: 38, 41, 42, 44, 45. Middle = 42 kg." }),
      pp({ question: "A bar chart shows 20 boys and 30 girls. What fraction of the class are boys?", options: ["2/5", "1/2", "3/5", "2/3"], answer: 0, explanation: "20/50 = 2/5." }),
      pp({ question: "The mean of 4 numbers is 15. A 5th number is added and the mean becomes 16. What is the 5th number?", options: ["17", "18", "19", "20"], answer: 3, explanation: "First 4 sum = 60. New sum = 80. Fifth = 80 − 60 = 20." }),
      pp({ question: "A pie chart shows 25% of students travel by bus. If there are 200 students, how many travel by bus?", options: ["25", "50", "75", "100"], answer: 1, explanation: "25% of 200 = 50." }),
      pp({ question: "The range of a set of numbers is 18. The smallest number is 7. What is the largest?", options: ["11", "18", "25", "126"], answer: 2, explanation: "Largest = 7 + 18 = 25." }),
      { question: "Find the mean of 6, 6, 12.", options: ["6", "8", "12", "24"], answer: 1, explanation: "24 ÷ 3 = 8." },
      { question: "Find the range of 3, 9, 2, 7, 5.", options: ["2", "5", "7", "9"], answer: 2, explanation: "9 − 2 = 7." },
      w({ question: "What is the median of 10, 3, 7, 15, 21? (just the number)", acceptAnswers: ["10"], explanation: "Sorted: 3, 7, 10, 15, 21. Middle = 10.", timeLimit: 20 }),
      w({ question: "The mean of 3, 7, 8, and x is 7. What is x? (just the number)", acceptAnswers: ["10"], explanation: "Sum must be 28. 3+7+8 = 18, so x = 10.", timeLimit: 30 }),
      pp(w({ question: "A pictogram uses one symbol = 4 apples. There are 6 symbols. How many apples total? (just the number)", acceptAnswers: ["24"], explanation: "6 × 4 = 24 apples." })),
    ],
  },
  {
    id: "cp6-algebra", name: "Algebra Basics", icon: "Sigma", description: "Variables, simple equations and patterns.",
    defaultTimeLimit: 30,
    theory: "Algebra uses letters (variables) to represent unknown numbers.\n\nIf x + 5 = 12, we can find x by subtracting 5 from both sides: x = 12 − 5 = 7.\n\nWe can simplify expressions by combining like terms: 3a + 2a = 5a.\n\nSequences follow rules. If a sequence goes 2, 5, 8, 11, ... the rule is 'add 3' each time. The nth term can be written as a formula.",
    questions: [
      { question: "If x + 7 = 15, what is x?", options: ["7", "8", "9", "15"], answer: 1, explanation: "x = 15 − 7 = 8." },
      { question: "Simplify 4a + 3a.", options: ["7a", "12a", "7", "a⁷"], answer: 0, explanation: "4a + 3a = 7a." },
      { question: "If 3x = 18, what is x?", options: ["5", "6", "7", "15"], answer: 1, explanation: "x = 18 ÷ 3 = 6." },
      { question: "What comes next? 2, 5, 8, 11, ___", options: ["12", "13", "14", "15"], answer: 2, explanation: "Adding 3 each time: 11 + 3 = 14." },
      { question: "If y = 2x + 1, what is y when x = 5?", options: ["7", "9", "10", "11"], answer: 3, explanation: "2(5) + 1 = 11." },
      pp({ question: "Solve: 2x + 3 = 17. What is x?", options: ["5", "7", "8.5", "14"], answer: 1, explanation: "2x = 14, so x = 7." }),
      pp({ question: "A number is doubled and then 8 is added to give 20. What is the number?", options: ["4", "6", "10", "12"], answer: 1, explanation: "2n + 8 = 20, so 2n = 12, n = 6." }),
      pp({ question: "Simplify 5x + 2 − 3x + 7.", options: ["2x + 9", "8x + 9", "2x − 5", "8x − 5"], answer: 0, explanation: "5x − 3x = 2x; 2 + 7 = 9, so 2x + 9." }),
      w({ question: "If x + 12 = 20, what is x? (just the number)", acceptAnswers: ["8"], explanation: "x = 20 − 12 = 8.", timeLimit: 15 }),
      w({ question: "Simplify 6b − 2b. (write as e.g. 4b)", acceptAnswers: ["4b"], explanation: "6b − 2b = 4b.", timeLimit: 15 }),
      { question: "What is the nth term of 3, 6, 9, 12, ...?", options: ["3n", "n + 3", "3n + 1", "n × 3 + 0"], answer: 0, explanation: "Each term is 3 × n, so 3n." },
      { question: "If a = 4, what is 3a + 2?", options: ["9", "12", "14", "20"], answer: 2, explanation: "3(4) + 2 = 14." },
      pp({ question: "Expand 2(x + 5).", options: ["2x + 10", "2x + 5", "2x + 7", "x + 10"], answer: 0, explanation: "2 × x = 2x, 2 × 5 = 10, so 2x + 10." }),
      w({ question: "Solve x − 9 = 3. What is x? (just the number)", acceptAnswers: ["12"], explanation: "x = 3 + 9 = 12.", timeLimit: 15 }),
      pp(w({ question: "The nth term of a sequence is 4n − 1. What is the 5th term? (just the number)", acceptAnswers: ["19"], explanation: "4(5) − 1 = 19." })),
    ],
  },
  {
    id: "cp6-fractions", name: "Fractions & Decimals", icon: "PieChart", description: "Equivalent fractions, comparing and converting.",
    defaultTimeLimit: 30,
    theory: "A fraction shows a part of a whole. The top number is the numerator, the bottom is the denominator.\n\nEquivalent fractions are worth the same amount: 1/2 = 2/4 = 3/6. You can make equivalent fractions by multiplying or dividing top and bottom by the same number.\n\nTo convert a fraction to a decimal, divide the numerator by the denominator: 3/4 = 3 ÷ 4 = 0.75.\n\nTo compare fractions, make the denominators the same, or convert them to decimals.",
    questions: [
      { question: "Which is bigger: 1/2 or 1/3?", options: ["1/2", "1/3", "Same", "Can't tell"], answer: 0, explanation: "1/2 = 0.5 and 1/3 ≈ 0.33, so 1/2 is bigger." },
      { question: "What is 2/4 simplified?", options: ["1/2", "1/4", "2/2", "1/3"], answer: 0, explanation: "Divide top and bottom by 2: 2/4 = 1/2." },
      { question: "Write 3/4 as a decimal.", options: ["0.34", "0.75", "0.5", "0.25"], answer: 1, explanation: "3 ÷ 4 = 0.75." },
      { question: "What is 1/3 + 1/3?", options: ["1/6", "2/3", "2/6", "1/9"], answer: 1, explanation: "Same denominator: 1/3 + 1/3 = 2/3." },
      { question: "Which is bigger: 2/3 or 3/5?", options: ["2/3", "3/5", "Same", "Can't tell"], answer: 0, explanation: "2/3 ≈ 0.67 and 3/5 = 0.6, so 2/3 is bigger." },
      pp({ question: "Calculate 1/2 + 1/4. Give your answer as a fraction.", options: ["2/6", "3/4", "1/6", "2/4"], answer: 1, explanation: "1/2 = 2/4, so 2/4 + 1/4 = 3/4." }),
      pp({ question: "Order from smallest to largest: 0.5, 0.45, 0.6, 0.55.", options: ["0.45, 0.5, 0.55, 0.6", "0.5, 0.45, 0.55, 0.6", "0.6, 0.55, 0.5, 0.45", "0.45, 0.6, 0.5, 0.55"], answer: 0, explanation: "0.45 < 0.5 < 0.55 < 0.6." }),
      pp({ question: "Write 0.125 as a fraction in its simplest form.", options: ["1/8", "1/4", "1/2", "125/1000"], answer: 0, explanation: "0.125 = 125/1000 = 1/8." }),
      w({ question: "What is 5/8 as a decimal?", acceptAnswers: ["0.625", ".625"], explanation: "5 ÷ 8 = 0.625.", timeLimit: 25 }),
      w({ question: "Simplify 6/9 to its lowest terms. (write as a/b)", acceptAnswers: ["2/3"], explanation: "Divide top and bottom by 3: 6/9 = 2/3.", timeLimit: 15 }),
      { question: "What is 3/5 as a percentage?", options: ["30%", "35%", "50%", "60%"], answer: 3, explanation: "3/5 = 0.6 = 60%." },
      { question: "Which fraction is equivalent to 1/2?", options: ["3/6", "2/3", "3/4", "1/5"], answer: 0, explanation: "3/6 = 1/2." },
      pp(w({ question: "What is 2/3 as a decimal? (round to 2 decimal places)", acceptAnswers: ["0.67", ".67", "0.6667", "0.66"], explanation: "2 ÷ 3 ≈ 0.67." })),
      w({ question: "What is 1/4 + 1/2? Give your answer as a fraction. (write as a/b)", acceptAnswers: ["3/4"], explanation: "1/4 + 2/4 = 3/4.", timeLimit: 20 }),
      { question: "Write 7/10 as a decimal.", options: ["0.7", "0.07", "0.71", "0.17"], answer: 0, explanation: "7 ÷ 10 = 0.7." },
    ],
  },
];

/* ===================== STAGE 6 SCIENCE ===================== */
export const CHECKPOINT_STAGE6_SCIENCE: Topic[] = [
  {
    id: "cp6-living-things", name: "Living Things", icon: "Leaf", description: "Plants, animals and the human body.",
    defaultTimeLimit: 30,
    theory: "All living things share seven life processes (MRS GREN): Movement, Respiration, Sensitivity, Growth, Reproduction, Excretion, Nutrition.\n\nPlants make their own food using photosynthesis: sunlight + carbon dioxide + water → glucose + oxygen. This happens in the leaves, which contain chlorophyll.\n\nAnimals can be grouped by what they eat: herbivores (plants only), carnivores (meat only), and omnivores (both).\n\nThe human body has major organs: the heart pumps blood, the brain controls the body, the lungs help us breathe, and the stomach digests food.",
    questions: [
      { question: "Which part of a plant makes food?", options: ["Roots", "Leaf", "Flower", "Stem"], answer: 1, explanation: "Leaves make food using sunlight (photosynthesis)." },
      { question: "What do we call animals that only eat plants?", options: ["Carnivores", "Herbivores", "Omnivores", "Predators"], answer: 1, explanation: "Herbivores eat only plants." },
      { question: "Which organ pumps blood around the body?", options: ["Lungs", "Brain", "Heart", "Liver"], answer: 2, explanation: "The heart pumps blood." },
      { question: "What gas do plants take in for photosynthesis?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], answer: 2, explanation: "Plants take in carbon dioxide and release oxygen." },
      { question: "Which part of the body controls everything we do?", options: ["Heart", "Brain", "Lungs", "Stomach"], answer: 1, explanation: "The brain controls the body." },
      { question: "What do we call animals that eat both meat and plants?", options: ["Carnivores", "Herbivores", "Omnivores", "Insectivores"], answer: 2, explanation: "Omnivores eat both." },
      pp({ question: "A food chain is: grass → rabbit → fox. If the fox has 100 units of energy, roughly how much did the rabbit have?", options: ["10 units", "100 units", "1000 units", "Same"], answer: 2, explanation: "Energy decreases by about 90% at each step, so the rabbit had about 10× the fox's energy ≈ 1000 units." }),
      pp({ question: "Why do plants have roots?", options: ["To make food", "To take in water and hold the plant", "To attract bees", "To release seeds"], answer: 1, explanation: "Roots absorb water and minerals and anchor the plant." }),
      pp({ question: "Which of these is NOT a vertebrate?", options: ["Fish", "Snake", "Butterfly", "Frog"], answer: 2, explanation: "A butterfly is an insect (invertebrate) — it has no backbone." }),
      pp({ question: "What is the main function of the leaves in a plant?", options: ["To hold the plant up", "To make food by photosynthesis", "To store water", "To attract insects"], answer: 1, explanation: "Leaves make food via photosynthesis." }),
      { question: "What do plants release during photosynthesis?", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: 1, explanation: "Plants release oxygen during photosynthesis." },
      { question: "Which life process is 'breathing'?", options: ["Respiration", "Movement", "Growth", "Sensitivity"], answer: 0, explanation: "Respiration is releasing energy from food — we breathe to take in oxygen for this." },
      w({ question: "What gas do humans breathe in?", acceptAnswers: ["oxygen", "O2", "O₂"], explanation: "We breathe in oxygen.", timeLimit: 15 }),
      w({ question: "What 'M' in MRS GREN means moving your body?", acceptAnswers: ["movement", "move"], explanation: "Movement is the M in MRS GREN.", timeLimit: 15 }),
      pp(w({ question: "In photosynthesis, plants take in carbon dioxide and release which gas?", acceptAnswers: ["oxygen", "O2", "O₂"], explanation: "Plants release oxygen." })),
    ],
  },
  {
    id: "cp6-materials", name: "Materials & States", icon: "FlaskConical", description: "Solids, liquids, gases and changes of state.",
    defaultTimeLimit: 30,
    theory: "Everything is made of matter, which exists in three main states: solid, liquid and gas.\n\nSolids keep their shape and have a fixed volume. Liquids take the shape of their container but keep a fixed volume. Gases spread out to fill any container.\n\nHeating a solid makes it melt into a liquid. Heating a liquid makes it evaporate into a gas. Cooling a gas makes it condense into a liquid. Cooling a liquid makes it freeze into a solid.\n\nSome changes are reversible (can be undone, like melting ice) and some are irreversible (cannot be undone, like burning wood or cooking an egg).",
    questions: [
      { question: "Which state of matter has a fixed shape and volume?", options: ["Solid", "Liquid", "Gas", "All"], answer: 0, explanation: "Solids have a fixed shape and volume." },
      { question: "What do we call the change from a liquid to a gas?", options: ["Melting", "Freezing", "Evaporation", "Condensation"], answer: 2, explanation: "Liquid to gas = evaporation." },
      { question: "At what temperature does water freeze (in °C)?", options: ["0°", "10°", "100°", "32°"], answer: 0, explanation: "Water freezes at 0°C." },
      { question: "What do we call the change from a gas to a liquid?", options: ["Melting", "Freezing", "Evaporation", "Condensation"], answer: 3, explanation: "Gas to liquid = condensation." },
      { question: "Which is a good conductor of electricity?", options: ["Plastic", "Wood", "Copper", "Rubber"], answer: 2, explanation: "Copper (a metal) conducts electricity." },
      { question: "At what temperature does water boil (in °C)?", options: ["50°", "90°", "100°", "212°"], answer: 2, explanation: "Water boils at 100°C." },
      pp({ question: "Iron rusts when it is exposed to which gas and what?", options: ["Nitrogen and heat", "Oxygen and water", "Carbon dioxide and light", "Hydrogen and salt"], answer: 1, explanation: "Rusting needs oxygen and water." }),
      pp({ question: "Salt dissolves in water. The salt is the ___ and the water is the ___.", options: ["Solute; solvent", "Solvent; solute", "Solution; solute", "Solute; solution"], answer: 0, explanation: "The dissolved substance is the solute; the liquid doing the dissolving is the solvent." }),
      pp({ question: "Which of these changes is reversible?", options: ["Burning wood", "Cooking an egg", "Melting chocolate", "Rusting iron"], answer: 2, explanation: "Melting chocolate can be reversed by cooling — the others cannot." }),
      pp({ question: "A solid is heated and turns into a liquid. What is this process called?", options: ["Freezing", "Melting", "Boiling", "Condensing"], answer: 1, explanation: "Solid to liquid = melting." }),
      { question: "Which of these is an irreversible change?", options: ["Melting ice", "Dissolving salt in water", "Burning paper", "Freezing water"], answer: 2, explanation: "Burning paper cannot be undone — it's irreversible." },
      { question: "A liquid takes the shape of its ___.", options: ["particles", "container", "molecules", "lid"], answer: 1, explanation: "Liquids flow to take the shape of their container." },
      w({ question: "What do we call a liquid turning into a gas?", acceptAnswers: ["evaporation", "evaporating"], explanation: "Liquid to gas = evaporation.", timeLimit: 15 }),
      w({ question: "What process happens when steam hits a cold window and turns to water?", acceptAnswers: ["condensation", "condensing"], explanation: "Gas to liquid = condensation.", timeLimit: 15 }),
      pp(w({ question: "Which material is a good thermal (heat) insulator: metal or plastic? (type one word)", acceptAnswers: ["plastic", "Plastic"], explanation: "Plastic is a poor conductor, so it's a good insulator." })),
    ],
  },
  {
    id: "cp6-forces", name: "Forces & Energy", icon: "Zap", description: "Pushes, pulls, friction and electricity.",
    defaultTimeLimit: 30,
    theory: "A force is a push or a pull. Forces can make things move, speed up, slow down, or change direction.\n\nGravity pulls objects towards the Earth. Friction is a force that slows things down when two surfaces rub together. Air resistance is friction in the air.\n\nMagnets attract magnetic materials like iron and steel. They have two poles: north and south. Opposite poles attract; like poles repel.\n\nElectricity flows in a circuit. A complete circuit needs a power source (battery), wires, and a device (like a bulb). If the circuit is broken, the electricity stops flowing.",
    questions: [
      { question: "What force pulls objects towards the Earth?", options: ["Friction", "Gravity", "Magnetism", "Upthrust"], answer: 1, explanation: "Gravity pulls objects down." },
      { question: "Which force slows down a moving bike?", options: ["Gravity", "Friction", "Magnetism", "Light"], answer: 1, explanation: "Friction slows moving things down." },
      { question: "What do we call a push or a pull?", options: ["A force", "Energy", "Speed", "Mass"], answer: 0, explanation: "A push or pull is a force." },
      { question: "Which of these is a source of light?", options: ["The Moon", "A mirror", "The Sun", "A book"], answer: 2, explanation: "The Sun gives out light; the Moon and mirror only reflect it." },
      { question: "What device changes electrical energy into light?", options: ["A wire", "A bulb", "A battery", "A switch"], answer: 1, explanation: "A bulb turns electrical energy into light." },
      { question: "Which is a magnetic material?", options: ["Plastic", "Wood", "Iron", "Glass"], answer: 2, explanation: "Iron is magnetic." },
      pp({ question: "A ball is dropped from a height. As it falls, which type of energy is increasing?", options: ["Chemical energy", "Kinetic energy", "Elastic energy", "Light energy"], answer: 1, explanation: "As it speeds up, its kinetic (movement) energy increases." }),
      pp({ question: "Why is friction useful between car tyres and the road?", options: ["It slows the car so it can stop", "It wastes energy", "It makes the car hot", "It does nothing useful"], answer: 0, explanation: "Friction lets tyres grip the road so the car can stop and turn safely." }),
      pp({ question: "A circuit has a battery, wires and a bulb, but the bulb does not light. Which is the most likely reason?", options: ["The bulb is broken or the circuit is incomplete", "The bulb is too bright", "There is too much wire", "The battery is too new"], answer: 0, explanation: "An incomplete circuit or broken bulb stops the current flowing." }),
      pp({ question: "Sound travels through which of these fastest?", options: ["Air", "Water", "A solid (metal)", "Vacuum"], answer: 2, explanation: "Sound travels fastest through solids because particles are closer together." }),
      { question: "Two magnets are placed north pole to north pole. What happens?", options: ["They attract", "They repel", "Nothing", "They stick"], answer: 1, explanation: "Like poles repel." },
      { question: "Which is a unit of force?", options: ["Joule", "Newton", "Watt", "Metre"], answer: 1, explanation: "Force is measured in Newtons (N)." },
      w({ question: "What force pulls things down to Earth? (one word)", acceptAnswers: ["gravity", "Gravity"], explanation: "Gravity pulls things down.", timeLimit: 10 }),
      w({ question: "What force slows things down when surfaces rub? (one word)", acceptAnswers: ["friction", "Friction"], explanation: "Friction slows things down.", timeLimit: 10 }),
      pp(w({ question: "A circuit must be ___ for electricity to flow. (one word)", acceptAnswers: ["complete", "closed", "connected"], explanation: "A complete (closed) circuit lets electricity flow." })),
    ],
  },
  {
    id: "cp6-earth-space", name: "Earth & Space", icon: "Globe", description: "The solar system, day and night, seasons and the moon.",
    defaultTimeLimit: 35,
    theory: "The Earth is one of eight planets that orbit (go around) the Sun. The Sun is a star at the centre of our solar system.\n\nThe Earth spins on its axis once every 24 hours — this gives us day and night. The Earth also orbits the Sun once every 365¼ days (one year).\n\nThe seasons happen because the Earth is tilted. When our part of the Earth leans towards the Sun, we get summer; when it leans away, we get winter.\n\nThe Moon orbits the Earth about once a month. We see different phases of the Moon (new, crescent, half, full) depending on how much of its lit side faces us.",
    questions: [
      { question: "What is at the centre of our solar system?", options: ["The Earth", "The Moon", "The Sun", "Jupiter"], answer: 2, explanation: "The Sun is at the centre." },
      { question: "How long does the Earth take to spin once on its axis?", options: ["12 hours", "24 hours", "30 days", "365 days"], answer: 1, explanation: "The Earth spins once every 24 hours — this gives us day and night." },
      { question: "How long does the Earth take to orbit the Sun once?", options: ["24 hours", "30 days", "365¼ days", "100 days"], answer: 2, explanation: "One orbit = 365¼ days (one year)." },
      { question: "Why do we have seasons?", options: ["The Earth gets closer to the Sun", "The Earth is tilted", "The Sun moves", "The Moon changes the weather"], answer: 1, explanation: "The Earth's tilt means different parts get more or less sunlight at different times of year." },
      { question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], answer: 1, explanation: "There are 8 planets." },
      { question: "What causes day and night?", options: ["The Earth orbiting the Sun", "The Earth spinning on its axis", "The Moon orbiting the Earth", "Clouds covering the Sun"], answer: 1, explanation: "The Earth spinning on its axis gives us day and night." },
      pp({ question: "Which planet is closest to the Sun?", options: ["Venus", "Earth", "Mercury", "Mars"], answer: 2, explanation: "Mercury is the closest planet to the Sun." }),
      pp({ question: "Why does the Moon appear to change shape during the month?", options: ["The Moon grows and shrinks", "We see different amounts of its lit side", "Clouds cover parts of it", "The Sun moves"], answer: 1, explanation: "We see different phases depending on how much of the Moon's lit side faces us." }),
      pp({ question: "Which is the largest planet in our solar system?", options: ["Earth", "Saturn", "Jupiter", "Neptune"], answer: 2, explanation: "Jupiter is the largest planet." }),
      pp({ question: "Why do we not feel the Earth moving?", options: ["It moves too slowly to feel", "It's not moving", "We're too heavy", "Gravity keeps us still"], answer: 0, explanation: "The Earth spins smoothly, so we don't feel the movement." }),
      { question: "When our part of Earth leans towards the Sun, what season do we get?", options: ["Winter", "Summer", "Spring only", "Autumn only"], answer: 1, explanation: "Leaning towards the Sun = summer (more direct sunlight)." },
      { question: "How often does the Moon orbit the Earth?", options: ["Every day", "About once a month", "Once a year", "Never"], answer: 1, explanation: "The Moon orbits the Earth about once a month." },
      w({ question: "What star is at the centre of our solar system? (one word)", acceptAnswers: ["the sun", "sun", "Sun", "the Sun"], explanation: "The Sun is the star at the centre.", timeLimit: 10 }),
      w({ question: "How many hours does it take for the Earth to spin once? (just the number)", acceptAnswers: ["24"], explanation: "The Earth spins once every 24 hours.", timeLimit: 10 }),
      pp(w({ question: "What do we call the path the Earth takes around the Sun? (one word)", acceptAnswers: ["orbit", "orbiting"], explanation: "The Earth orbits the Sun." })),
    ],
  },
];

/* ===================== STAGE 9 MATHS ===================== */
export const CHECKPOINT_STAGE9_MATHS: Topic[] = [
  {
    id: "cp9-number", name: "Number & Calculation", icon: "Hash", description: "Powers, standard form and percentages.",
    defaultTimeLimit: 35,
    theory: "Standard form (scientific notation) is a way to write very large or very small numbers.\n\nA number in standard form looks like A × 10ⁿ, where A is between 1 and 10. For example, 45,000 = 4.5 × 10⁴ (move the decimal 4 places left).\n\nFor very small numbers: 0.00036 = 3.6 × 10⁻⁴ (move the decimal 4 places right, making the power negative).\n\nWhen multiplying powers with the same base, add the indices: 2⁴ × 2³ = 2⁷. A negative index means a reciprocal: 3⁻² = 1/3² = 1/9.\n\nPercentage change = (change ÷ original) × 100. Simple interest = P × R × T (principal × rate × time).",
    questions: [
      { question: "What is 2⁴ × 2³? (leave as a power of 2)", options: ["2⁷", "2¹²", "2⁴", "4⁷"], answer: 0, explanation: "Add the indices: 4 + 3 = 7, so 2⁷." },
      { question: "Write 45,000 in standard form.", options: ["4.5 × 10⁴", "45 × 10³", "4.5 × 10⁵", "0.45 × 10⁵"], answer: 0, explanation: "Move the decimal 4 places: 4.5 × 10⁴." },
      { question: "What is 3⁻² as a fraction?", options: ["1/9", "1/6", "−6", "1/3"], answer: 0, explanation: "3⁻² = 1/3² = 1/9." },
      { question: "Increase 250 by 12%.", options: ["262", "270", "280", "290"], answer: 2, explanation: "12% of 250 = 30, so 250 + 30 = 280." },
      { question: "Express 0.4 as a fraction in its simplest form.", options: ["4/10", "2/5", "1/4", "4/100"], answer: 1, explanation: "0.4 = 4/10 = 2/5." },
      pp({ question: "Calculate (3.2 × 10⁵) + (4.8 × 10⁵). Give your answer in standard form.", options: ["8 × 10⁵", "8 × 10¹⁰", "7.2 × 10²⁵", "8 × 10⁴"], answer: 0, explanation: "Same powers, add coefficients: 3.2 + 4.8 = 8, so 8 × 10⁵." }),
      pp({ question: "A coat costs $80. It is reduced by 15% in a sale. What is the sale price?", options: ["$65", "$68", "$70", "$72"], answer: 1, explanation: "15% of $80 = $12. $80 − $12 = $68." }),
      pp({ question: "A bank pays 3% simple interest per year. How much interest is earned on £500 in 4 years?", options: ["£15", "£50", "£60", "£65"], answer: 2, explanation: "Interest = 500 × 0.03 × 4 = £60." }),
      pp({ question: "Write 0.00036 in standard form.", options: ["3.6 × 10⁻⁴", "3.6 × 10⁻³", "36 × 10⁻⁴", "3.6 × 10⁴"], answer: 0, explanation: "Move the decimal 4 places right: 3.6 × 10⁻⁴." }),
      pp({ question: "Find 28% of $350.", options: ["$84", "$95", "$98", "$108"], answer: 2, explanation: "0.28 × 350 = $98." }),
      { question: "What is 5⁰?", options: ["0", "1", "5", "undefined"], answer: 1, explanation: "Any number to the power 0 equals 1." },
      { question: "Calculate (2 × 10³) × (3 × 10⁴). Give answer in standard form.", options: ["6 × 10⁷", "6 × 10¹²", "5 × 10⁷", "6 × 10⁴"], answer: 0, explanation: "2 × 3 = 6, and 10³ × 10⁴ = 10⁷, so 6 × 10⁷." },
      w({ question: "Write 720,000 in standard form. (use the format A x 10^n)", acceptAnswers: ["7.2 x 10^5", "7.2 × 10^5", "7.2x10^5", "7.2×10⁵"], explanation: "720,000 = 7.2 × 10⁵.", timeLimit: 25 }),
      w({ question: "Decrease 400 by 15%. What is the result? (just the number)", acceptAnswers: ["340"], explanation: "15% of 400 = 60, so 400 − 60 = 340.", timeLimit: 25 }),
      pp(w({ question: "Write 0.0005 in standard form. (use the format A x 10^n)", acceptAnswers: ["5 x 10^-4", "5 × 10^-4", "5x10^-4", "5×10⁻⁴"], explanation: "0.0005 = 5 × 10⁻⁴." })),
    ],
  },
  {
    id: "cp9-algebra", name: "Algebra", icon: "Sigma", description: "Equations, formulas and sequences.",
    defaultTimeLimit: 40,
    theory: "Algebra lets us solve problems with unknown values represented by letters.\n\nTo solve an equation, do the same operation to both sides to isolate the unknown. For 3(x − 2) = 2(x + 4): expand to get 3x − 6 = 2x + 8, then move x terms: x = 14.\n\nFactorising means taking out a common factor: 6x² + 9x = 3x(2x + 3).\n\nThe nth term of a linear sequence like 4, 9, 14, 19, ... follows the rule 5n − 1 (the difference is 5, and 5×1 − 1 = 4 for the first term).",
    questions: [
      { question: "Solve 5x − 7 = 2x + 8.", options: ["3", "5", "7", "15"], answer: 1, explanation: "3x = 15, so x = 5." },
      { question: "Expand and simplify 3(2x + 1) + 2(x − 4).", options: ["8x − 5", "8x + 11", "6x − 5", "8x − 1"], answer: 0, explanation: "6x + 3 + 2x − 8 = 8x − 5." },
      { question: "Factorise 6x² + 9x.", options: ["3x(2x + 3)", "3(2x² + 3x)", "6x(x + 3)", "x(6x + 9)"], answer: 0, explanation: "Common factor 3x: 3x(2x + 3)." },
      { question: "If y = 2x + 3, find y when x = −2.", options: ["−1", "1", "7", "−7"], answer: 0, explanation: "2(−2) + 3 = −4 + 3 = −1." },
      { question: "What is the nth term of 4, 9, 14, 19, ...?", options: ["5n − 1", "5n", "4n + 5", "n + 4"], answer: 0, explanation: "Difference is 5; first term 4 = 5×1 − 1, so 5n − 1." },
      pp({ question: "Solve the equation 3(x − 2) = 2(x + 4).", options: ["2", "7", "14", "10"], answer: 2, explanation: "3x − 6 = 2x + 8, so x = 14." }),
      pp({ question: "The formula C = 5/9 (F − 32) converts Fahrenheit to Celsius. Find C when F = 50.", options: ["5°", "10°", "18°", "22°"], answer: 1, explanation: "C = 5/9 × (50 − 32) = 5/9 × 18 = 10°." }),
      pp({ question: "Make x the subject of the formula y = 4x − 7.", options: ["x = (y + 7)/4", "x = (y − 7)/4", "x = 4y − 7", "x = y/4 + 7"], answer: 0, explanation: "y + 7 = 4x, so x = (y + 7)/4." }),
      pp({ question: "Find the value of 3x² − 2x when x = −1.", options: ["5", "1", "−5", "−1"], answer: 0, explanation: "3(1) − 2(−1) = 3 + 2 = 5." }),
      pp({ question: "A sequence starts 2, 6, 12, 20, 30, ... What is the next term?", options: ["36", "40", "42", "44"], answer: 2, explanation: "Differences are 4, 6, 8, 10, so next difference is 12: 30 + 12 = 42." }),
      { question: "Solve 4(x + 1) = 20.", options: ["3", "4", "5", "6"], answer: 1, explanation: "4x + 4 = 20, so 4x = 16, x = 4." },
      { question: "Simplify 7x − 3 − 2x + 8.", options: ["5x + 5", "9x + 5", "5x − 11", "5x + 11"], answer: 0, explanation: "7x − 2x = 5x; −3 + 8 = 5, so 5x + 5." },
      w({ question: "Solve 2x + 9 = 21. What is x? (just the number)", acceptAnswers: ["6"], explanation: "2x = 12, x = 6.", timeLimit: 20 }),
      w({ question: "What is the nth term of 3, 7, 11, 15, ...? (use format like 4n-1)", acceptAnswers: ["4n-1", "4n - 1", "4n−1"], explanation: "Difference is 4, first term 3 = 4×1 − 1, so 4n − 1.", timeLimit: 30 }),
      pp(w({ question: "Factorise x² − 16. (write as (a)(b) format)", acceptAnswers: ["(x-4)(x+4)", "(x+4)(x-4)", "(x - 4)(x + 4)", "(x + 4)(x - 4)"], explanation: "Difference of squares: (x − 4)(x + 4)." })),
    ],
  },
  {
    id: "cp9-geometry", name: "Geometry & Trigonometry", icon: "Triangle", description: "Pythagoras, angles and transformations.",
    defaultTimeLimit: 40,
    theory: "Pythagoras' theorem: in a right-angled triangle, a² + b² = c², where c is the hypotenuse (longest side, opposite the right angle).\n\nThe area of a circle = π × r². The circumference = 2 × π × r. The volume of a cylinder = π × r² × h.\n\nBearings are angles measured clockwise from North, written as 3 digits (e.g. 045°). The bearing of A from B is the reverse bearing: add 180°.\n\nSurface area of a cuboid = 2(lw + lh + wh) — the sum of all 6 faces.",
    questions: [
      { question: "A right triangle has legs 9 cm and 12 cm. What is the hypotenuse?", options: ["15 cm", "18 cm", "21 cm", "144 cm"], answer: 0, explanation: "81 + 144 = 225, √225 = 15 cm." },
      { question: "What is the area of a circle with radius 5 cm? (π ≈ 3.14)", options: ["31.4 cm²", "78.5 cm²", "157 cm²", "25 cm²"], answer: 1, explanation: "π × 5² = 3.14 × 25 = 78.5 cm²." },
      { question: "Angles in a triangle add to 180°. What is the third angle if the other two are 48° and 67°?", options: ["55°", "65°", "75°", "85°"], answer: 1, explanation: "180 − 48 − 67 = 65°." },
      { question: "What is the volume of a cylinder with radius 3 cm and height 10 cm? (π ≈ 3.14)", options: ["94.2 cm³", "188.4 cm³", "282.6 cm³", "314 cm³"], answer: 2, explanation: "π × 3² × 10 = 3.14 × 90 = 282.6 cm³." },
      { question: "A 90° rotation clockwise turns a shape. How many right angles is that?", options: ["1", "2", "3", "4"], answer: 0, explanation: "90° = 1 right angle." },
      pp({ question: "Calculate the length of the hypotenuse of a right-angled triangle with the other two sides 7 cm and 24 cm.", options: ["25 cm", "26 cm", "31 cm", "576 cm"], answer: 0, explanation: "49 + 576 = 625, √625 = 25 cm." }),
      pp({ question: "A circle has a circumference of 62.8 cm. Using π ≈ 3.14, what is its radius?", options: ["10 cm", "20 cm", "31.4 cm", "5 cm"], answer: 0, explanation: "C = 2πr, so r = 62.8 ÷ 6.28 = 10 cm." }),
      pp({ question: "A triangle is drawn on a grid with vertices A(1,1), B(5,1) and C(5,4). What is its area?", options: ["6 units²", "8 units²", "12 units²", "10 units²"], answer: 0, explanation: "Base AB = 4, height = 3. Area = ½ × 4 × 3 = 6 units²." }),
      pp({ question: "The bearing of B from A is 135°. What is the bearing of A from B?", options: ["315°", "45°", "225°", "135°"], answer: 0, explanation: "Bearing of A from B = 135 + 180 = 315°." }),
      pp({ question: "A cuboid has dimensions 4 cm × 6 cm × 5 cm. What is its total surface area?", options: ["74 cm²", "120 cm²", "148 cm²", "60 cm²"], answer: 2, explanation: "2(4×6 + 4×5 + 6×5) = 2(24 + 20 + 30) = 2 × 74 = 148 cm²." }),
      { question: "A right triangle has a hypotenuse of 15 cm and one leg of 9 cm. What is the other leg?", options: ["10 cm", "12 cm", "13 cm", "14 cm"], answer: 1, explanation: "225 − 81 = 144, √144 = 12 cm." },
      { question: "What is the circumference of a circle with radius 7 cm? (π = 22/7)", options: ["44 cm", "154 cm", "22 cm", "49 cm"], answer: 0, explanation: "2 × 22/7 × 7 = 44 cm." },
      w({ question: "A right triangle has legs 8 cm and 6 cm. What is the hypotenuse in cm? (just the number)", acceptAnswers: ["10"], explanation: "64 + 36 = 100, √100 = 10 cm.", timeLimit: 25 }),
      w({ question: "Angles on a straight line add to 180°. One angle is 72°. What is the other in degrees? (just the number)", acceptAnswers: ["108"], explanation: "180 − 72 = 108°.", timeLimit: 15 }),
      pp(w({ question: "A circle has radius 14 cm. Using π = 22/7, what is its area in cm²? (just the number)", acceptAnswers: ["616"], explanation: "22/7 × 14² = 22/7 × 196 = 616 cm²." })),
    ],
  },
  {
    id: "cp9-statistics", name: "Statistics & Probability", icon: "BarChart3", description: "Averages, probability, tree diagrams and Venn diagrams.",
    defaultTimeLimit: 35,
    theory: "There are three averages: mean (total ÷ count), median (middle value), and mode (most common value). The range = highest − lowest.\n\nProbability measures how likely something is. It's written as a fraction or decimal from 0 (impossible) to 1 (certain). P(event) = number of favourable outcomes ÷ total outcomes.\n\nFor independent events, P(A and B) = P(A) × P(B). A tree diagram helps calculate combined probabilities by multiplying along branches.\n\nA Venn diagram uses overlapping circles to show how groups are related. The overlapping region shows items in both groups.",
    questions: [
      { question: "Find the mean of 6, 10, 14, 18.", options: ["10", "12", "14", "48"], answer: 1, explanation: "Sum = 48, ÷ 4 = 12." },
      { question: "Find the median of 5, 9, 12, 15, 20.", options: ["9", "12", "15", "20"], answer: 1, explanation: "Middle of 5 sorted numbers = 12." },
      { question: "A bag has 4 red and 6 blue balls. P(blue)?", options: ["0.4", "0.6", "0.1", "0.5"], answer: 1, explanation: "6/10 = 0.6." },
      { question: "P(event) = 0.25. What is P(not event)?", options: ["0.25", "0.5", "0.75", "1.0"], answer: 2, explanation: "1 − 0.25 = 0.75." },
      { question: "Two coins are tossed. P(both heads)?", options: ["1/2", "1/3", "1/4", "1/8"], answer: 2, explanation: "HH, HT, TH, TT — 1 of 4 = 1/4." },
      pp({ question: "A dice is rolled. P(rolling a prime number)?", options: ["1/6", "1/3", "1/2", "2/3"], answer: 2, explanation: "Primes on a die: 2, 3, 5 = 3/6 = 1/2." }),
      pp({ question: "A biased coin has P(heads) = 0.7. It's tossed twice. P(both heads)?", options: ["0.14", "0.49", "0.7", "1.4"], answer: 1, explanation: "0.7 × 0.7 = 0.49." }),
      pp({ question: "In a class of 30, 18 play football and 12 play basketball. 5 play both. How many play neither?", options: ["3", "5", "7", "12"], answer: 1, explanation: "18 + 12 − 5 = 25 play at least one. 30 − 25 = 5 play neither." }),
      { question: "Find the range of 15, 3, 22, 8, 17.", options: ["8", "17", "19", "22"], answer: 2, explanation: "22 − 3 = 19." },
      { question: "Find the mode of 7, 4, 7, 9, 7, 2, 4.", options: ["2", "4", "7", "9"], answer: 2, explanation: "7 appears 3 times — the most." },
      pp({ question: "The mean of 5 numbers is 8. A 6th number, 14, is added. What is the new mean?", options: ["8", "9", "10", "11"], answer: 1, explanation: "Old sum = 40. New sum = 54. New mean = 54/6 = 9." }),
      { question: "A spinner has 5 equal sections numbered 1-5. P(landing on an odd number)?", options: ["1/5", "2/5", "3/5", "1/2"], answer: 2, explanation: "Odd: 1, 3, 5 = 3 of 5 = 3/5." },
      w({ question: "What is the median of 4, 8, 15, 16, 23? (just the number)", acceptAnswers: ["15"], explanation: "Middle of 5 sorted numbers = 15.", timeLimit: 15 }),
      w({ question: "A bag has 5 red and 15 blue balls. What is P(red) as a decimal?", acceptAnswers: ["0.25", ".25"], explanation: "5/20 = 0.25.", timeLimit: 20 }),
      pp(w({ question: "P(A) = 0.4 and P(B) = 0.5, independent. What is P(A and B)?", acceptAnswers: ["0.2", ".2"], explanation: "0.4 × 0.5 = 0.2." })),
    ],
  },
];

/* ===================== STAGE 9 SCIENCE ===================== */
export const CHECKPOINT_STAGE9_SCIENCE: Topic[] = [
  {
    id: "cp9-biology", name: "Biology", icon: "Leaf", description: "Cells, reproduction and ecosystems.",
    defaultTimeLimit: 35,
    theory: "All living things are made of cells. The cell is the basic unit of life.\n\nKey parts of a cell: the nucleus controls the cell and contains DNA; the cell membrane controls what enters and leaves; the cytoplasm is where reactions happen; mitochondria release energy (respiration); chloroplasts (plant cells only) carry out photosynthesis.\n\nPhotosynthesis: plants make food using sunlight, carbon dioxide and water, releasing oxygen. Respiration: all living things release energy from food using oxygen, releasing carbon dioxide.\n\nCells → tissues → organs → organ systems → organism. Arteries carry blood away from the heart; veins carry it back.",
    questions: [
      { question: "What is the basic unit of life?", options: ["Atom", "Cell", "Organ", "Tissue"], answer: 1, explanation: "The cell is the basic unit of life." },
      { question: "Which part of the cell controls what enters and leaves?", options: ["Nucleus", "Cell membrane", "Cytoplasm", "Cell wall"], answer: 1, explanation: "The cell membrane controls what enters and leaves." },
      { question: "What is photosynthesis?", options: ["Plants making food from sunlight", "Animals breathing", "Roots taking in water", "Flowers making seeds"], answer: 0, explanation: "Photosynthesis = plants making food using sunlight, CO₂ and water." },
      { question: "Which gas do we breathe in?", options: ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], answer: 1, explanation: "We breathe in oxygen." },
      { question: "Where in the cell is genetic material (DNA) found?", options: ["Cell wall", "Nucleus", "Membrane", "Vacuole"], answer: 1, explanation: "DNA is in the nucleus." },
      pp({ question: "A plant is placed in a dark cupboard for 3 days. What happens to the starch in its leaves?", options: ["It increases", "It is used up and disappears", "It stays the same", "It turns into sugar"], answer: 1, explanation: "Without light, the plant can't photosynthesise, so it uses up stored starch." }),
      pp({ question: "Which blood vessels carry blood away from the heart?", options: ["Veins", "Arteries", "Capillaries", "All of them"], answer: 1, explanation: "Arteries carry blood away from the heart; veins carry it back." }),
      pp({ question: "In a food web, what organism is always at the start?", options: ["Predator", "Producer (plant)", "Decomposer", "Herbivore"], answer: 1, explanation: "Producers (plants) make the food that everything else depends on." }),
      pp({ question: "What is the word for a group of the same organism living in one place?", options: ["Community", "Population", "Ecosystem", "Habitat"], answer: 1, explanation: "A population is all the individuals of one species in an area." }),
      pp({ question: "Why is the leaf flat and thin?", options: ["To look pretty", "To catch maximum light and allow gas exchange", "To store water", "To stop animals eating it"], answer: 1, explanation: "A flat, thin leaf has a large surface area to absorb light and allow gases to diffuse." }),
      { question: "Which organelle releases energy in respiration?", options: ["Nucleus", "Mitochondria", "Chloroplast", "Vacuole"], answer: 1, explanation: "Mitochondria are the site of respiration." },
      { question: "Which is found in plant cells but NOT animal cells?", options: ["Nucleus", "Cell membrane", "Chloroplast", "Mitochondria"], answer: 2, explanation: "Chloroplasts are only in plant cells (for photosynthesis)." },
      w({ question: "What process do plants use to make food? (one word)", acceptAnswers: ["photosynthesis"], explanation: "Photosynthesis makes food from sunlight.", timeLimit: 15 }),
      w({ question: "Which part of the cell contains DNA? (one word)", acceptAnswers: ["nucleus", "the nucleus"], explanation: "DNA is stored in the nucleus.", timeLimit: 15 }),
      pp(w({ question: "What gas do plants release during photosynthesis? (one word)", acceptAnswers: ["oxygen", "O2", "O₂"], explanation: "Plants release oxygen." })),
    ],
  },
  {
    id: "cp9-chemistry", name: "Chemistry", icon: "FlaskConical", description: "Atoms, elements, reactions and acids.",
    defaultTimeLimit: 35,
    theory: "Everything is made of atoms. An element is made of only one type of atom. A compound has two or more different atoms joined together (e.g. water H₂O).\n\nThe atomic number = number of protons. The mass number = protons + neutrons. Isotopes have the same number of protons but different numbers of neutrons.\n\nAcids have pH below 7, neutral is pH 7, and bases (alkalis) have pH above 7. When a metal reacts with an acid, it produces a salt and hydrogen gas.\n\nUniversal indicator shows pH: red for strong acid, green for neutral, blue/purple for strong base.",
    questions: [
      { question: "What is the smallest part of an element?", options: ["Molecule", "Atom", "Cell", "Compound"], answer: 1, explanation: "An atom is the smallest part of an element." },
      { question: "What is the chemical symbol for water?", options: ["H₂O", "CO₂", "O₂", "NaCl"], answer: 0, explanation: "Water is H₂O — two hydrogen, one oxygen." },
      { question: "Which is an example of an element?", options: ["Water", "Salt", "Oxygen", "Air"], answer: 2, explanation: "Oxygen is an element (only one type of atom)." },
      { question: "What is the pH of a neutral solution?", options: ["0", "7", "14", "1"], answer: 1, explanation: "Neutral pH = 7." },
      { question: "Which gas is produced when a metal reacts with an acid?", options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], answer: 2, explanation: "Metal + acid → salt + hydrogen." },
      pp({ question: "When magnesium burns in air, what is the white powder formed?", options: ["Magnesium oxide", "Magnesium carbonate", "Magnesium hydroxide only", "Carbon dioxide"], answer: 0, explanation: "Magnesium + oxygen → magnesium oxide (a white powder)." }),
      pp({ question: "Which of these is a compound?", options: ["O₂", "Fe", "CO₂", "Ne"], answer: 2, explanation: "CO₂ has two different elements joined, so it's a compound." }),
      pp({ question: "What colour is universal indicator in a strong acid?", options: ["Green", "Blue", "Red", "Purple"], answer: 2, explanation: "Strong acids turn universal indicator red." }),
      pp({ question: "What happens to the particles in a solid when it is heated?", options: ["They stop moving", "They move faster and spread out", "They disappear", "They get heavier"], answer: 1, explanation: "Heating makes particles move faster and spread apart." }),
      pp({ question: "Calcium carbonate (limestone) breaks down when heated strongly. What gas is given off?", options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], answer: 2, explanation: "Thermal decomposition of limestone releases CO₂." }),
      { question: "What is the atomic number of carbon?", options: ["4", "6", "8", "12"], answer: 1, explanation: "Carbon has 6 protons, so atomic number = 6." },
      { question: "Which is a base (alkali)?", options: ["HCl", "NaOH", "HNO₃", "H₂SO₄"], answer: 1, explanation: "NaOH (sodium hydroxide) is a base." },
      w({ question: "What gas is released when a metal reacts with an acid? (one word)", acceptAnswers: ["hydrogen", "H2", "H₂"], explanation: "Metal + acid → salt + hydrogen.", timeLimit: 15 }),
      w({ question: "What is the pH of a neutral solution? (just the number)", acceptAnswers: ["7"], explanation: "Neutral pH = 7.", timeLimit: 10 }),
      pp(w({ question: "An atom has 11 protons and 12 neutrons. What is its mass number? (just the number)", acceptAnswers: ["23"], explanation: "Mass number = 11 + 12 = 23." })),
    ],
  },
  {
    id: "cp9-physics", name: "Physics", icon: "Zap", description: "Motion, energy, waves and electricity.",
    defaultTimeLimit: 35,
    theory: "Forces and motion: speed = distance ÷ time. Acceleration = change in speed ÷ time. Force is measured in Newtons (N). Newton's 2nd law: Force = mass × acceleration.\n\nEnergy: measured in Joules (J). Kinetic energy = ½ × m × v². Gravitational potential energy = m × g × h. Power = energy ÷ time, measured in Watts (W). Work = force × distance.\n\nElectricity: Current = charge ÷ time (Amperes). Ohm's law: Voltage = Current × Resistance (V = IR). Energy = V × I × t.\n\nWaves: speed = frequency × wavelength. Sound travels fastest in solids, slowest in air.",
    questions: [
      { question: "What is the unit of force?", options: ["Joule", "Newton", "Watt", "Metre"], answer: 1, explanation: "Force is measured in Newtons (N)." },
      { question: "Speed = distance ÷ ?", options: ["Time", "Force", "Mass", "Energy"], answer: 0, explanation: "Speed = distance ÷ time." },
      { question: "What is the unit of energy?", options: ["Newton", "Joule", "Watt", "Ampere"], answer: 1, explanation: "Energy is measured in Joules (J)." },
      { question: "What type of energy does a stretched spring store?", options: ["Kinetic", "Elastic (strain)", "Chemical", "Nuclear"], answer: 1, explanation: "A stretched spring stores elastic potential energy." },
      { question: "What is the current in a circuit if 12 C of charge flows in 4 s?", options: ["3 A", "48 A", "8 A", "0.33 A"], answer: 0, explanation: "Current = charge ÷ time = 12 ÷ 4 = 3 A." },
      pp({ question: "A car travels 180 km in 3 hours. What is its average speed?", options: ["45 km/h", "54 km/h", "60 km/h", "90 km/h"], answer: 2, explanation: "Speed = 180 ÷ 3 = 60 km/h." }),
      pp({ question: "Calculate the work done when a force of 20 N moves an object 5 m.", options: ["4 J", "25 J", "100 J", "15 J"], answer: 2, explanation: "Work = force × distance = 20 × 5 = 100 J." }),
      pp({ question: "A wave has a frequency of 10 Hz and a wavelength of 3 m. What is its speed?", options: ["3.3 m/s", "30 m/s", "13 m/s", "0.3 m/s"], answer: 1, explanation: "Speed = frequency × wavelength = 10 × 3 = 30 m/s." }),
      pp({ question: "Using V = IR, find the voltage when current is 2 A and resistance is 6 Ω.", options: ["3 V", "8 V", "12 V", "0.33 V"], answer: 2, explanation: "V = 2 × 6 = 12 V." }),
      pp({ question: "A stone is dropped from a cliff. As it falls, what energy change happens?", options: ["Chemical to light", "Gravitational potential to kinetic", "Kinetic to potential", "Heat to sound"], answer: 1, explanation: "Potential energy is converted to kinetic energy as it falls." }),
      { question: "What is the power output if 600 J of work is done in 12 s?", options: ["50 W", "5 W", "72 W", "7200 W"], answer: 0, explanation: "Power = 600 ÷ 12 = 50 W." },
      { question: "Calculate the kinetic energy of a 2 kg ball moving at 6 m/s.", options: ["12 J", "36 J", "72 J", "6 J"], answer: 1, explanation: "KE = ½ × 2 × 6² = 36 J." },
      w({ question: "What is the unit of electrical resistance? (one word)", acceptAnswers: ["ohm", "ohms", "Ω"], explanation: "Resistance is measured in Ohms (Ω).", timeLimit: 15 }),
      w({ question: "A 6 V battery drives 2 A through a resistor. What is the resistance in ohms? (just the number)", acceptAnswers: ["3"], explanation: "R = V/I = 6/2 = 3 Ω.", timeLimit: 20 }),
      pp(w({ question: "Calculate the work done when a 15 N force moves an object 8 m. (just the number, in joules)", acceptAnswers: ["120"], explanation: "Work = 15 × 8 = 120 J." })),
    ],
  },
  {
    id: "cp9-earth-science", name: "Earth & Environment", icon: "Globe", description: "Rock cycle, weathering, atmosphere and climate.",
    defaultTimeLimit: 35,
    theory: "The rock cycle shows how rocks change from one type to another over time.\n\nThree main rock types: igneous (formed from cooled magma/lava), sedimentary (formed from compressed sediments), and metamorphic (formed when existing rocks are changed by heat and pressure).\n\nWeathering breaks rocks down: physical weathering (freeze-thaw, wind), chemical weathering (acid rain), and biological weathering (plant roots).\n\nThe atmosphere is made up of about 78% nitrogen, 21% oxygen, and small amounts of other gases including carbon dioxide. The greenhouse effect traps heat — too much CO₂ from burning fossil fuels causes climate change.",
    questions: [
      { question: "Which type of rock forms when magma or lava cools?", options: ["Sedimentary", "Metamorphic", "Igneous", "All three"], answer: 2, explanation: "Igneous rock forms from cooled magma or lava." },
      { question: "What percentage of the atmosphere is oxygen?", options: ["21%", "78%", "1%", "50%"], answer: 0, explanation: "The atmosphere is about 21% oxygen." },
      { question: "Which gas is the main cause of the greenhouse effect?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], answer: 2, explanation: "Carbon dioxide traps heat in the atmosphere." },
      { question: "What type of rock is limestone?", options: ["Igneous", "Sedimentary", "Metamorphic", "None"], answer: 1, explanation: "Limestone is a sedimentary rock formed from compressed sediments." },
      { question: "Which of these is an example of physical weathering?", options: ["Acid rain dissolving rock", "Plant roots cracking rock", "Freeze-thaw cracking rock", "Bacteria breaking rock"], answer: 2, explanation: "Freeze-thaw is physical weathering — water freezes and expands, cracking the rock." },
      pp({ question: "Which gas makes up about 78% of the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Argon"], answer: 1, explanation: "Nitrogen makes up about 78% of the atmosphere." }),
      pp({ question: "Sedimentary rocks are formed by...", options: ["Cooling of magma", "Heat and pressure on other rocks", "Compression of sediments over time", "Volcanic eruption"], answer: 2, explanation: "Sedimentary rocks form when sediments are compressed and cemented over time." }),
      pp({ question: "Metamorphic rocks form when...", options: ["Sediments are compressed", "Existing rocks are changed by heat and pressure", "Magma cools quickly", "Rocks are weathered"], answer: 1, explanation: "Metamorphic rocks form when existing rocks are changed by heat and pressure." }),
      pp({ question: "Which human activity increases CO₂ in the atmosphere most?", options: ["Planting trees", "Burning fossil fuels", "Recycling", "Using solar power"], answer: 1, explanation: "Burning fossil fuels releases large amounts of CO₂." }),
      pp({ question: "Acid rain is caused by which gases mixing with rain?", options: ["Oxygen and nitrogen", "Sulfur dioxide and nitrogen oxides", "Carbon dioxide only", "Hydrogen and helium"], answer: 1, explanation: "Sulfur dioxide and nitrogen oxides mix with rain to form acid rain." }),
      { question: "What is the process called when water freezes in rock cracks and breaks the rock?", options: ["Chemical weathering", "Freeze-thaw weathering", "Erosion", "Deposition"], answer: 1, explanation: "Freeze-thaw weathering — water expands when it freezes, cracking the rock." },
      { question: "Marble is an example of which rock type?", options: ["Igneous", "Sedimentary", "Metamorphic", "None"], answer: 2, explanation: "Marble is metamorphic — formed from limestone under heat and pressure." },
      w({ question: "What type of rock forms from cooled lava? (one word)", acceptAnswers: ["igneous"], explanation: "Igneous rock forms from cooled magma or lava.", timeLimit: 15 }),
      w({ question: "What is the most abundant gas in the atmosphere? (one word)", acceptAnswers: ["nitrogen"], explanation: "Nitrogen makes up ~78% of the atmosphere.", timeLimit: 15 }),
      pp(w({ question: "What rock type is formed by compression of sediments? (one word)", acceptAnswers: ["sedimentary"], explanation: "Sedimentary rocks form from compressed sediments." })),
    ],
  },
  {
    id: "cp9-organisms", name: "Organisms & Environment", icon: "Leaf", description: "Adaptation, variation, classification and feeding relationships.",
    defaultTimeLimit: 35,
    theory: "Organisms are adapted to their environment. A cactus stores water and has spines (for dry deserts). A polar bear has thick fur and blubber (for cold Arctic).\n\nVariation means differences between individuals. It can be continuous (height, weight) or discontinuous (blood group, eye colour). Variation comes from genetics (inherited) and environment.\n\nClassification sorts organisms into groups: kingdom → phylum → class → order → family → genus → species.\n\nFeeding relationships: producer (plant) → primary consumer (herbivore) → secondary consumer (carnivore) → tertiary consumer. A food web shows many connected food chains. Energy is lost at each level.",
    questions: [
      { question: "A cactus has spines instead of leaves. How is this an adaptation?", options: ["To attract insects", "To reduce water loss in dry conditions", "To grow taller", "To make food faster"], answer: 1, explanation: "Spines reduce water loss — an adaptation to desert life." },
      { question: "Which is an example of continuous variation?", options: ["Blood group", "Eye colour", "Height", "Attached earlobes"], answer: 2, explanation: "Height is continuous (any value in a range); the others are discontinuous." },
      { question: "In a food chain, what is a producer?", options: ["A carnivore", "A plant that makes its own food", "A decomposer", "A herbivore"], answer: 1, explanation: "Producers (plants) make their own food by photosynthesis." },
      { question: "Why is energy lost at each step in a food chain?", options: ["Animals eat too much", "Most energy is lost as heat and waste", "Plants don't make enough", "The chain is too short"], answer: 1, explanation: "Only about 10% of energy passes to the next level — the rest is lost as heat and waste." },
      { question: "Which is a primary consumer?", options: ["Grass", "Rabbit", "Fox", "Eagle"], answer: 1, explanation: "A rabbit eats plants (a producer), so it's a primary consumer." },
      pp({ question: "A polar bear has thick blubber and white fur. This is an adaptation to...", options: ["A desert", "The Arctic (cold, snowy)", "A rainforest", "The ocean floor"], answer: 1, explanation: "Blubber keeps it warm; white fur camouflages it in snow — Arctic adaptations." }),
      pp({ question: "Which is caused by environmental variation (not inherited)?", options: ["Eye colour", "Blood group", "A suntan", "Natural hair colour"], answer: 2, explanation: "A suntan is caused by sunlight (environment), not inherited." }),
      pp({ question: "In classification, which group is the most specific (smallest)?", options: ["Kingdom", "Class", "Genus", "Species"], answer: 3, explanation: "Species is the most specific level — organisms that can breed and produce fertile offspring." }),
      pp({ question: "In a food web, what happens if the number of primary consumers decreases?", options: ["Producers increase, secondary consumers decrease", "Everything stays the same", "Producers decrease, secondary consumers increase", "Only decomposers change"], answer: 0, explanation: "Fewer herbivores = more plants (producers) and less food for carnivores (secondary consumers decrease)." }),
      pp({ question: "Which is an example of discontinuous variation?", options: ["Height", "Weight", "Blood group", "Foot length"], answer: 2, explanation: "Blood group has distinct categories (A, B, AB, O) — discontinuous." }),
      { question: "What do we call a consumer that eats only meat?", options: ["Herbivore", "Carnivore", "Omnivore", "Producer"], answer: 1, explanation: "A carnivore eats only meat." },
      { question: "Which kingdom do humans belong to?", options: ["Plantae", "Fungi", "Animalia", "Protista"], answer: 2, explanation: "Humans are in the kingdom Animalia (animals)." },
      w({ question: "What do we call a plant in a food chain? (one word)", acceptAnswers: ["producer", "producers"], explanation: "Plants are producers — they make their own food.", timeLimit: 15 }),
      w({ question: "What word means differences between individuals of the same species? (one word)", acceptAnswers: ["variation"], explanation: "Variation = differences between individuals.", timeLimit: 15 }),
      pp(w({ question: "What is an animal that eats both plants and meat called? (one word)", acceptAnswers: ["omnivore", "omnivores"], explanation: "An omnivore eats both plants and meat." })),
    ],
  },
];

export const CHECKPOINT_CONTENT: Record<CheckpointStage, Record<CheckpointSubject, Topic[]>> = {
  stage6: { maths: CHECKPOINT_STAGE6_MATHS, science: CHECKPOINT_STAGE6_SCIENCE },
  stage9: { maths: CHECKPOINT_STAGE9_MATHS, science: CHECKPOINT_STAGE9_SCIENCE },
};

export const CHECKPOINT_SUBJECTS: { id: CheckpointSubject; name: string; icon: string; color: string; description: string }[] = [
  { id: "maths", name: "Maths", icon: "Sigma", color: "#a855f7", description: "Number, algebra, geometry, fractions and data handling with past-paper questions." },
  { id: "science", name: "Science", icon: "FlaskConical", color: "#34d399", description: "Biology, chemistry, physics, earth science and environment — everything you need for Checkpoint science." },
];

export function getCheckpointTopics(stage: CheckpointStage, subject: CheckpointSubject): Topic[] {
  return CHECKPOINT_CONTENT[stage][subject];
}
