// ===== IGCSE content: Core + Elective subjects with exam-style topics =====

import type { Topic, Question } from "./quizData";
import type { IgcseSubjectId } from "./quizData";

const pp = (q: Question): Question => ({ ...q, pastPaper: true, cambridge: true });

export type IgcseSubjectInfo = {
  id: IgcseSubjectId;
  name: string;
  icon: string;
  color: string;
  core: boolean; // true = core (compulsory), false = elective
  description: string;
  topics: Topic[];
};

/* ===================== MATHEMATICS (CORE) ===================== */
const IGCSE_MATHS_TOPICS: Topic[] = [
  {
    id: "ig-maths-number",
    name: "Number",
    icon: "Hash",
    description: "Standard form, percentages, ratio and proportion.",
    questions: [
      { question: "Write 0.000 42 in standard form.", options: ["4.2 × 10⁻⁴", "4.2 × 10⁻³", "42 × 10⁻⁵", "4.2 × 10⁴"], answer: 0, explanation: "Move the decimal 4 places right: 4.2 × 10⁻⁴." },
      { question: "Calculate (2.5 × 10⁴) × (4 × 10³). Give your answer in standard form.", options: ["1 × 10⁸", "10 × 10⁷", "1 × 10⁷", "6.5 × 10⁷"], answer: 0, explanation: "2.5 × 4 = 10, and 10⁴ × 10³ = 10⁷. So 10 × 10⁷ = 1 × 10⁸." },
      { question: "Increase $250 by 18%.", options: ["$268", "$280", "$295", "$300"], answer: 2, explanation: "18% of 250 = 45, so 250 + 45 = $295." },
      { question: "A sum of $5000 earns 4% compound interest per year. What is the total after 2 years?", options: ["$5400", "$5408", "$5410", "$5450"], answer: 1, explanation: "5000 × 1.04² = 5000 × 1.0816 = $5408." },
      pp({ question: "A car loses 12% of its value each year. A car bought for $18,000 is worth how much after 2 years?", options: ["$13,939", "$15,840", "$13,766", "$15,400"], answer: 0, explanation: "18000 × 0.88² = 18000 × 0.7744 = $13,939.20 ≈ $13,939." }),
      pp({ question: "Share $720 in the ratio 3:2:1. What is the largest share?", options: ["$120", "$240", "$360", "$420"], answer: 2, explanation: "6 parts total, $720÷6 = $120 each. Largest = 3 × $120 = $360." }),
      pp({ question: "y is inversely proportional to x. When x = 4, y = 12. Find y when x = 6.", options: ["8", "9", "18", "6"], answer: 0, explanation: "y = k/x, so k = 4×12 = 48. When x = 6: y = 48/6 = 8." }),
      pp({ question: "Calculate 2/5 + 1/3. Give your answer as a fraction.", options: ["3/15", "11/15", "3/8", "5/15"], answer: 1, explanation: "Common denominator 15: 6/15 + 5/15 = 11/15." }),
      pp({ question: "A train travels 240 km in 2 h 30 min. Calculate the average speed in km/h.", options: ["80 km/h", "90 km/h", "96 km/h", "100 km/h"], answer: 2, explanation: "2 h 30 min = 2.5 h. Speed = 240 ÷ 2.5 = 96 km/h." }),
      pp({ question: "The price of a jacket is reduced from $85 to $68. What is the percentage reduction?", options: ["15%", "17%", "20%", "25%"], answer: 2, explanation: "Reduction = $17. 17/85 = 0.20 = 20%." }),
    ],
  },
  {
    id: "ig-maths-algebra",
    name: "Algebra",
    icon: "Sigma",
    description: "Equations, factorising, sequences and functions.",
    questions: [
      { question: "Solve 3(x − 4) = 2(x + 5).", options: ["22", "10", "20", "7"], answer: 0, explanation: "3x − 12 = 2x + 10, so x = 22." },
      { question: "Factorise x² − 9.", options: ["(x − 3)(x + 3)", "(x − 9)(x + 1)", "(x − 3)²", "(x + 3)²"], answer: 0, explanation: "Difference of squares: (x − 3)(x + 3)." },
      { question: "Factorise x² + 7x + 12.", options: ["(x + 3)(x + 4)", "(x + 2)(x + 6)", "(x + 1)(x + 12)", "(x + 3)²"], answer: 0, explanation: "3 + 4 = 7 and 3 × 4 = 12." },
      { question: "Simplify (3x²y) × (4xy³).", options: ["12x³y⁴", "7x²y³", "12x²y³", "12x³y"], answer: 0, explanation: "3 × 4 = 12; x² × x = x³; y × y³ = y⁴." },
      { question: "What is the nth term of 5, 11, 17, 23, ...?", options: ["6n − 1", "6n", "5n + 6", "n + 5"], answer: 0, explanation: "Difference 6; first term 5 = 6×1 − 1, so 6n − 1." },
      pp({ question: "Solve the simultaneous equations: 3x + 2y = 13 and x − 2y = −3.", options: ["x = 2, y = 3.5", "x = 2.5, y = 2.75", "x = 3, y = 2", "x = 4, y = 0.5"], answer: 1, explanation: "Adding: 4x = 10, x = 2.5. Then 3(2.5) + 2y = 13 → 2y = 5.5 → y = 2.75." }),
      pp({ question: "Solve x² − 5x + 6 = 0.", options: ["x = 2 or 3", "x = 1 or 6", "x = −2 or −3", "x = 6 or −1"], answer: 0, explanation: "Factorise: (x − 2)(x − 3) = 0, so x = 2 or 3." }),
      pp({ question: "Make x the subject of A = πx².", options: ["x = √(A/π)", "x = A/2π", "x = π/A", "x = A²/π"], answer: 0, explanation: "A/π = x², so x = √(A/π)." }),
      pp({ question: "f(x) = 2x + 1 and g(x) = x². Find fg(3).", options: ["19", "37", "13", "7"], answer: 0, explanation: "g(3) = 9, then f(9) = 2(9) + 1 = 19." }),
      pp({ question: "Rearrange y = mx + c to make x the subject.", options: ["x = (y − c)/m", "x = y/m − c", "x = (y + c)/m", "x = my + c"], answer: 0, explanation: "y − c = mx, so x = (y − c)/m." }),
    ],
  },
  {
    id: "ig-maths-geometry",
    name: "Geometry & Mensuration",
    icon: "Shapes",
    description: "Angles, circles, area, volume and trigonometry.",
    questions: [
      { question: "A right-angled triangle has legs 8 cm and 15 cm. What is the hypotenuse?", options: ["17 cm", "23 cm", "12 cm", "21 cm"], answer: 0, explanation: "64 + 225 = 289, √289 = 17 cm." },
      { question: "A circle has radius 7 cm. What is its area? (π = 22/7)", options: ["154 cm²", "44 cm²", "49π cm²", "22 cm²"], answer: 0, explanation: "π × 7² = 22/7 × 49 = 154 cm²." },
      { question: "In a right triangle, sin(θ) = 0.5. What is θ?", options: ["30°", "45°", "60°", "90°"], answer: 0, explanation: "sin(30°) = 0.5." },
      { question: "A cylinder has radius 5 cm and height 12 cm. What is its volume? (π ≈ 3.14)", options: ["942 cm³", "471 cm³", "314 cm³", "188 cm³"], answer: 0, explanation: "π × 25 × 12 = 3.14 × 300 = 942 cm³." },
      pp({ question: "Calculate the area of a sector of a circle of radius 10 cm with angle 90°. (π ≈ 3.14)", options: ["78.5 cm²", "31.4 cm²", "157 cm²", "25 cm²"], answer: 0, explanation: "90°/360° = 1/4 of circle area. 3.14 × 100 × 1/4 = 78.5 cm²." }),
      pp({ question: "A cone has radius 6 cm and slant height 10 cm. What is its curved surface area? (π ≈ 3.14)", options: ["188.4 cm²", "113.0 cm²", "314 cm²", "376.8 cm²"], answer: 0, explanation: "πrl = 3.14 × 6 × 10 = 188.4 cm²." }),
      pp({ question: "In triangle ABC, angle A = 40°, angle B = 75°. Find angle C.", options: ["55°", "65°", "75°", "85°"], answer: 1, explanation: "180 − 40 − 75 = 65°." }),
      pp({ question: "A ship travels 30 km on a bearing of 090°, then 40 km due north. How far is it from the start?", options: ["50 km", "70 km", "10 km", "25 km"], answer: 0, explanation: "Pythagoras: √(30² + 40²) = √2500 = 50 km." }),
      pp({ question: "The volume of a sphere is 904.32 cm³. Using π ≈ 3.14, find its radius.", options: ["6 cm", "12 cm", "3 cm", "9 cm"], answer: 0, explanation: "V = 4/3 πr³. r³ = 904.32 × 3/(4 × 3.14) = 216, so r = 6 cm." }),
      pp({ question: "Two similar triangles have sides in ratio 2:5. The area of the smaller is 16 cm². What is the area of the larger?", options: ["40 cm²", "80 cm²", "100 cm²", "64 cm²"], answer: 2, explanation: "Area ratio = (2/5)² = 4/25. Larger area = 16 × 25/4 = 100 cm²." }),
    ],
  },
  {
    id: "ig-maths-statistics",
    name: "Statistics & Probability",
    icon: "BarChart3",
    description: "Averages, histograms, probability and tree diagrams.",
    questions: [
      { question: "Find the median of 7, 3, 9, 12, 5, 8, 10.", options: ["7", "8", "9", "10"], answer: 1, explanation: "Sorted: 3,5,7,8,9,10,12. Middle (4th) = 8." },
      { question: "A bag has 4 red and 6 blue balls. What is P(red) as a decimal?", options: ["0.4", "0.6", "0.04", "0.5"], answer: 0, explanation: "4/10 = 0.4." },
      { question: "Two coins are tossed. What is P(both tails)?", options: ["1/4", "1/2", "1/3", "1/8"], answer: 0, explanation: "TT is 1 of 4 outcomes = 1/4." },
      pp({ question: "A dice is rolled. What is P(rolling a number greater than 4)?", options: ["1/3", "1/2", "1/6", "2/3"], answer: 0, explanation: "Greater than 4: {5, 6} = 2/6 = 1/3." }),
      pp({ question: "In a survey of 200 students, 80 travel by bus. What angle on a pie chart represents bus travel?", options: ["144°", "120°", "80°", "160°"], answer: 0, explanation: "80/200 × 360 = 144°." }),
      pp({ question: "The mean of 5 numbers is 14. A 6th number, 20, is added. What is the new mean?", options: ["14", "15", "16", "17"], answer: 1, explanation: "Original sum = 70. New sum = 90. New mean = 90/6 = 15." }),
      pp({ question: "A biased coin has P(heads) = 0.6. It is tossed twice. P(both heads)?", options: ["0.36", "0.12", "0.24", "0.6"], answer: 0, explanation: "0.6 × 0.6 = 0.36." }),
      pp({ question: "On a tree diagram, P(A) = 0.3 and P(B) = 0.4, independent. Find P(A and B).", options: ["0.12", "0.7", "0.34", "0.07"], answer: 0, explanation: "Independent: 0.3 × 0.4 = 0.12." }),
      pp({ question: "A frequency table shows 50 values with total 850. What is the mean?", options: ["15", "17", "19", "20"], answer: 1, explanation: "850 ÷ 50 = 17." }),
      pp({ question: "P(event) = 0.25. What are the odds against the event?", options: ["3:1", "1:3", "1:4", "4:1"], answer: 0, explanation: "P(not) = 0.75. Odds against = 0.75:0.25 = 3:1." }),
    ],
  },
  {
    id: "ig-maths-calculus",
    name: "Calculus Basics",
    icon: "Sigma",
    description: "Differentiation, gradients and simple integration.",
    theory: "Calculus is the study of rates of change. Differentiation finds the gradient (rate of change) of a curve at any point. If y = x^n, then dy/dx = n·x^(n−1). For example, d/dx(x³) = 3x². The derivative of a constant is 0, and for a sum you differentiate each term separately: d/dx(3x² + 2x + 1) = 6x + 2.\nTo find the gradient of a curve at a specific point, first differentiate to get dy/dx, then substitute the x-value. For y = x², dy/dx = 2x, so at x = 3 the gradient is 6.\nIntegration is the reverse of differentiation. The integral of x^n is (x^(n+1))/(n+1) + c, where c is the constant of integration. For example, ∫2x dx = x² + c. Integration is used to find areas under curves.",
    defaultTimeLimit: 45,
    questions: [
      { question: "What is the derivative of x³?", options: ["3x²", "x²", "3x", "x⁴"], answer: 0, explanation: "Using the power rule: d/dx(x^n) = n·x^(n−1), so d/dx(x³) = 3x².", timeLimit: 30 },
      { question: "Differentiate 4x².", options: ["8x", "4x", "8", "8x²"], answer: 0, explanation: "d/dx(4x²) = 4 × 2x = 8x.", timeLimit: 25 },
      { question: "Find dy/dx when y = 5x.", type: "written", options: [], answer: 0, acceptAnswers: ["5"], explanation: "d/dx(5x) = 5.", timeLimit: 20 },
      { question: "What is the derivative of a constant, e.g. d/dx(7)?", options: ["0", "7", "7x", "1"], answer: 0, explanation: "The derivative of any constant is 0 — it doesn't change.", timeLimit: 20 },
      pp({ question: "Differentiate y = 3x² + 2x + 1.", type: "written", options: [], answer: 0, acceptAnswers: ["6x + 2", "6x+2"], explanation: "Differentiate each term: d/dx(3x²) = 6x, d/dx(2x) = 2, d/dx(1) = 0. So dy/dx = 6x + 2.", timeLimit: 35 }),
      pp({ question: "The derivative of x⁵ is...", options: ["5x⁴", "x⁴", "5x", "x⁶"], answer: 0, explanation: "Power rule: d/dx(x⁵) = 5x⁴.", timeLimit: 25 }),
      pp({ question: "Integration is the ___ of differentiation.", options: ["reverse", "square", "sum", "derivative"], answer: 0, explanation: "Integration reverses differentiation — it finds the original function from its derivative.", timeLimit: 25 }),
      { question: "Find the gradient of y = x² at x = 3.", type: "written", options: [], answer: 0, acceptAnswers: ["6"], explanation: "dy/dx = 2x. At x = 3: 2 × 3 = 6.", timeLimit: 35 },
      { question: "What is ∫2x dx?", options: ["x² + c", "x²", "2x² + c", "2 + c"], answer: 0, explanation: "∫x^n dx = x^(n+1)/(n+1) + c. ∫2x dx = 2·x²/2 + c = x² + c.", timeLimit: 30 },
      { question: "Evaluate ∫4x³ dx.", type: "written", options: [], answer: 0, acceptAnswers: ["x^4 + c", "x⁴ + c", "x^4+c", "x⁴+c"], explanation: "∫4x³ dx = 4·x⁴/4 + c = x⁴ + c.", timeLimit: 35 },
    ],
  },
];

/* ===================== ENGLISH (CORE) ===================== */
const IGCSE_ENGLISH_TOPICS: Topic[] = [
  {
    id: "ig-english-grammar",
    name: "Grammar & Punctuation",
    icon: "PenLine",
    description: "Sentence structure, clauses and punctuation.",
    questions: [
      { question: "Which is a complete sentence?", options: ["Running fast.", "Because it rained.", "She writes letters every week.", "Under the table."], answer: 2, explanation: "It has a subject (she) and a verb (writes)." },
      { question: "Which word is a conjunction?", options: ["slowly", "and", "table", "happy"], answer: 1, explanation: "And is a conjunction joining words or clauses." },
      { question: "Where should the apostrophe go? 'The students books were wet.'", options: ["The student's books", "The students' books", "No apostrophe needed", "The students's books"], answer: 1, explanation: "Plural possessive — books belonging to multiple students: students'." },
      { question: "Which is a subordinate clause?", options: ["I went home", "She laughed", "Although it was late", "They ran fast"], answer: 2, explanation: "'Although it was late' cannot stand alone — it's subordinate." },
      pp({ question: "Choose the correct sentence.", options: ["Me and Tom went to the shop.", "Tom and me went to the shop.", "Tom and I went to the shop.", "I and Tom went to the shop."], answer: 2, explanation: "When the subject, use 'Tom and I' — 'I' is the subject pronoun." }),
      pp({ question: "Which is the passive form of 'The dog chased the cat'?", options: ["The cat chased the dog", "The cat was chased by the dog", "The cat is chasing the dog", "The dog is chased by the cat"], answer: 1, explanation: "Passive: subject becomes object — 'The cat was chased by the dog.'" }),
      pp({ question: "Which sentence uses the correct homophone?", options: ["Their going to the park.", "There going to the park.", "They're going to the park.", "Theirs going to the park."], answer: 2, explanation: "They're = they are." }),
      pp({ question: "Which is a complex sentence?", options: ["I like tea.", "I like tea and coffee.", "I like tea because it is warm.", "Tea is warm."], answer: 2, explanation: "A complex sentence has a main clause + subordinate clause." }),
      pp({ question: "Punctuate correctly: 'what time is it asked sana'", options: ["What time is it? Asked Sana.", "What time is it, asked Sana?", "\"What time is it?\" asked Sana.", "what time is it asked sana"], answer: 2, explanation: "Direct speech needs quotation marks, a capital to start, and the reporting clause." }),
      pp({ question: "Which sentence is in the past perfect tense?", options: ["I had finished my homework before dinner.", "I finished my homework.", "I will finish my homework.", "I am finishing my homework."], answer: 0, explanation: "Past perfect = had + past participle (had finished)." }),
    ],
  },
  {
    id: "ig-english-comprehension",
    name: "Reading Comprehension",
    icon: "BookOpen",
    description: "Inference, analysis and writer's effects.",
    questions: [
      { question: "What does 'infer' mean in reading?", options: ["To guess with no clues", "To work out meaning from clues in the text", "To read aloud", "To copy the text"], answer: 1, explanation: "Inference = working out meaning using clues." },
      { question: "Which question helps you infer a character's feelings?", options: ["What is their name?", "How might they feel and why?", "What year is it?", "Where do they live?"], answer: 1, explanation: "Inference questions ask 'how' and 'why' about feelings and motives." },
      pp({ question: "Read: 'The sky wept grey tears all morning.' Which technique is used?", options: ["Simile", "Metaphor", "Personification", "Alliteration"], answer: 2, explanation: "Giving the sky human actions (weeping) is personification." }),
      pp({ question: "Read: 'The room was silent. The clock ticked loudly.' What mood is created?", options: ["Excitement", "Tension / unease", "Joy", "Anger"], answer: 1, explanation: "The contrast of silence and a loud tick builds tension." }),
      pp({ question: "A writer describes a character as 'a lion in battle'. This is a...", options: ["Metaphor", "Simile", "Personification", "Hyperbole"], answer: 0, explanation: "Saying someone 'is' a lion (with no 'like' or 'as') is a metaphor." }),
      pp({ question: "What is the purpose of a topic sentence?", options: ["To end the paragraph", "To introduce the main idea of the paragraph", "To rhyme", "To ask a question"], answer: 1, explanation: "A topic sentence states the paragraph's main idea." }),
      pp({ question: "Read: 'She slammed the door, her face burning.' What does 'burning' suggest?", options: ["She was cold", "She was angry or embarrassed", "The door was on fire", "She was tired"], answer: 1, explanation: "'Burning' face suggests anger or embarrassment." }),
      pp({ question: "Which is a fact (not opinion)?", options: ["Pizza is delicious.", "Water boils at 100°C at sea level.", "Football is the best sport.", "Summer is the nicest season."], answer: 1, explanation: "A fact can be proven; boiling point is a measurable fact." }),
      pp({ question: "What does 'tone' mean in a text?", options: ["The writer's attitude towards the subject", "The font size", "The number of words", "The page number"], answer: 0, explanation: "Tone = the writer's attitude or feeling towards the subject." }),
      pp({ question: "Read: 'The old bridge groaned under the weight.' Which word is personified?", options: ["old", "bridge", "groaned", "weight"], answer: 2, explanation: "'Groaned' gives the bridge a human action — personification." }),
    ],
  },
  {
    id: "ig-english-writing",
    name: "Directed Writing",
    icon: "PenLine",
    description: "Formal letters, reports, articles, tone and structure.",
    theory: "Directed writing asks you to produce a specific text type for a particular audience and purpose. Common formats include formal letters, reports, newspaper articles, speeches and diary entries. Each has its own layout and conventions. A formal letter begins with the sender's address and date, then 'Dear Sir/Madam,' and ends with 'Yours faithfully,' (when you don't know the name) or 'Yours sincerely,' (when you do).\nA report has a clear title, an introduction, organised sections (often with sub-headings) and a conclusion that summarises findings and may give recommendations. Reports use formal, objective language and present information in a logical order.\nA newspaper article needs a catchy headline, a lead paragraph that answers who/what/when/where, and short paragraphs. Use an appropriate tone — persuasive writing should be confident and emotive, while a report should be neutral and factual. Always plan your structure with a clear beginning, middle and end.",
    defaultTimeLimit: 45,
    questions: [
      { question: "How should a formal letter begin if you don't know the recipient's name?", options: ["Hi there,", "Dear Sir/Madam,", "Hello friend,", "To whom it may concern,", "Hey,"], answer: 1, explanation: "When you don't know the name, use 'Dear Sir/Madam,' followed by 'Yours faithfully' at the close.", timeLimit: 25 },
      { question: "In a report, what should the conclusion do?", options: ["Introduce a new topic", "Summarise findings and possibly make recommendations", "List all the data again", "Thank the reader"], answer: 1, explanation: "A report's conclusion summarises the main findings and may recommend actions.", timeLimit: 25 },
      { question: "Which complimentary close is used in a formal letter when you know the recipient's name?", type: "written", options: [], answer: 0, acceptAnswers: ["Yours sincerely", "Yours Sincerely", "yours sincerely"], explanation: "Use 'Yours sincerely' when you addressed the person by name; 'Yours faithfully' when you used Dear Sir/Madam.", timeLimit: 25 },
      { question: "A newspaper article should have a ___ that grabs the reader's attention.", options: ["headline", "footnote", "index", "bibliography"], answer: 0, explanation: "The headline is designed to grab attention and summarise the story.", timeLimit: 20 },
      pp({ question: "What is the purpose of a topic sentence in directed writing?", type: "written", options: [], answer: 0, acceptAnswers: ["to introduce the main idea of the paragraph", "introduce the main idea", "to introduce the main idea", "introduce the main idea of the paragraph", "to state the main idea of the paragraph"], explanation: "A topic sentence introduces the main idea of the paragraph, guiding the reader.", timeLimit: 35 }),
      pp({ question: "A formal letter should use ___ language.", options: ["slang and abbreviations", "formal and objective", "emoticons", "text-speak"], answer: 1, explanation: "Formal letters use formal, objective language — no slang or contractions.", timeLimit: 25 }),
      pp({ question: "In a report, the information should be presented in a ___ order.", options: ["random", "logical", "reverse", "alphabetical"], answer: 1, explanation: "Reports present information in a logical, structured order with clear sections.", timeLimit: 25 }),
      { question: "What tone should a persuasive article use?", options: ["Neutral and boring", "Confident and persuasive", "Aggressive and rude", "Unsure and hesitant"], answer: 1, explanation: "Persuasive writing uses a confident, persuasive tone to convince the reader.", timeLimit: 25 },
      { question: "State one feature of a formal letter's layout.", type: "written", options: [], answer: 0, acceptAnswers: ["sender's address", "recipient's address", "date", "salutation", "signature", "complimentary close", "dear sir", "dear madam", "yours faithfully", "yours sincerely"], explanation: "Formal letters include the sender's address, date, recipient's address, salutation, body, complimentary close and signature.", timeLimit: 30 },
      { question: "In directed writing, the word 'recount' means to...", options: ["Make up a fictional story", "Tell the story of what happened", "Persuade the reader", "Describe a place"], answer: 1, explanation: "To recount means to retell events in the order they happened.", timeLimit: 25 },
    ],
  },
];

/* ===================== PHYSICS (ELECTIVE) ===================== */
const IGCSE_PHYSICS_TOPICS: Topic[] = [
  {
    id: "ig-phy-motion",
    name: "Forces & Motion",
    icon: "Zap",
    description: "Speed, acceleration, Newton's laws and momentum.",
    questions: [
      { question: "What is the unit of acceleration?", options: ["m/s", "m/s²", "kg", "N"], answer: 1, explanation: "Acceleration is measured in metres per second squared (m/s²)." },
      { question: "A car accelerates from rest to 30 m/s in 6 s. What is its acceleration?", options: ["5 m/s²", "6 m/s²", "36 m/s²", "180 m/s²"], answer: 0, explanation: "a = Δv/t = 30/6 = 5 m/s²." },
      { question: "Newton's 2nd law: Force = ?", options: ["mass × velocity", "mass × acceleration", "weight × time", "momentum × time"], answer: 1, explanation: "F = ma." },
      { question: "A force of 24 N accelerates a 4 kg mass. What is the acceleration?", options: ["6 m/s²", "96 m/s²", "20 m/s²", "0.17 m/s²"], answer: 0, explanation: "a = F/m = 24/4 = 6 m/s²." },
      pp({ question: "A car of mass 1200 kg travelling at 20 m/s brakes to a stop in 5 s. What is the braking force?", options: ["4800 N", "2400 N", "6000 N", "9600 N"], answer: 0, explanation: "a = 20/5 = 4 m/s² (deceleration). F = 1200 × 4 = 4800 N." }),
      pp({ question: "Calculate the momentum of a 0.5 kg ball moving at 12 m/s.", options: ["6 kg·m/s", "24 kg·m/s", "0.04 kg·m/s", "12 kg·m/s"], answer: 0, explanation: "p = mv = 0.5 × 12 = 6 kg·m/s." }),
      pp({ question: "A 1500 kg car collides and stops in 0.3 s. Its initial speed was 20 m/s. What is the average force on the car?", options: ["10,000 N", "100,000 N", "3000 N", "4500 N"], answer: 1, explanation: "Δp = 1500 × 20 = 30,000. F = Δp/t = 30,000/0.3 = 100,000 N." }),
      pp({ question: "Which of these has the greatest weight on Earth?", options: ["1 kg of feathers", "1 kg of iron", "10 N of steel", "They all weigh about the same"], answer: 3, explanation: "1 kg of feathers and 1 kg of iron both weigh ~10 N, and 10 N of steel also weighs 10 N — so they all weigh about the same." }),
      pp({ question: "A ball is dropped. Ignoring air resistance, which statement is true?", options: ["It accelerates at 10 m/s²", "It falls at constant speed", "It slows down", "It stops in mid-air"], answer: 0, explanation: "Free fall acceleration ≈ 9.8 ≈ 10 m/s²." }),
      pp({ question: "Terminal velocity happens when...", options: ["A falling object's weight equals air resistance", "The object speeds up forever", "There is no gravity", "The object is in a vacuum"], answer: 0, explanation: "At terminal velocity, weight = air resistance, so net force is zero and speed is constant." }),
    ],
  },
  {
    id: "ig-phy-energy",
    name: "Energy & Work",
    icon: "Flame",
    description: "Energy stores, work, power and efficiency.",
    questions: [
      { question: "What is the unit of work?", options: ["Joule", "Watt", "Newton", "Pascal"], answer: 0, explanation: "Work is measured in Joules (J)." },
      { question: "Calculate the work done lifting a 20 N load 3 m vertically.", options: ["23 J", "60 J", "6.7 J", "17 J"], answer: 1, explanation: "Work = force × distance = 20 × 3 = 60 J." },
      { question: "What is the unit of power?", options: ["Joule", "Watt", "Newton", "Volt"], answer: 1, explanation: "Power is measured in Watts (W)." },
      { question: "A machine does 600 J of work in 12 s. What is its power?", options: ["50 W", "5 W", "72 W", "7200 W"], answer: 0, explanation: "P = W/t = 600/12 = 50 W." },
      pp({ question: "Calculate the kinetic energy of a 2 kg ball moving at 6 m/s.", options: ["12 J", "36 J", "72 J", "6 J"], answer: 1, explanation: "KE = ½ × 2 × 6² = ½ × 2 × 36 = 36 J." }),
      pp({ question: "A motor raises a 50 kg load 4 m in 10 s. (g = 10 m/s²) What is its power output?", options: ["200 W", "20 W", "500 W", "2000 W"], answer: 0, explanation: "Work = mgh = 50 × 10 × 4 = 2000 J. Power = 2000/10 = 200 W." }),
      pp({ question: "A machine uses 500 J of energy to output 400 J of useful work. What is its efficiency?", options: ["80%", "125%", "20%", "90%"], answer: 0, explanation: "Efficiency = 400/500 × 100 = 80%." }),
      pp({ question: "Which is NOT a renewable energy source?", options: ["Solar", "Wind", "Coal", "Hydroelectric"], answer: 2, explanation: "Coal is a fossil fuel — non-renewable." }),
      pp({ question: "Gravitational potential energy = ?", options: ["mgh", "½mv²", "mcΔT", "VIt"], answer: 0, explanation: "GPE = mgh." }),
      pp({ question: "A heater converts 80% of electrical energy into heat. If it uses 1500 J, how much useful heat is produced?", options: ["1200 J", "1500 J", "300 J", "960 J"], answer: 0, explanation: "0.80 × 1500 = 1200 J." }),
    ],
  },
  {
    id: "ig-phy-electricity",
    name: "Electricity",
    icon: "Plug",
    description: "Current, voltage, resistance and circuits.",
    questions: [
      { question: "What is the unit of electrical charge?", options: ["Coulomb", "Ampere", "Volt", "Ohm"], answer: 0, explanation: "Charge is measured in Coulombs (C)." },
      { question: "Ohm's law: V = ?", options: ["IR", "I/R", "R/I", "I + R"], answer: 0, explanation: "V = IR." },
      { question: "A 6 V battery drives 2 A through a resistor. What is the resistance?", options: ["3 Ω", "12 Ω", "0.33 Ω", "8 Ω"], answer: 0, explanation: "R = V/I = 6/2 = 3 Ω." },
      { question: "What is the current when 12 V is applied across a 4 Ω resistor?", options: ["3 A", "48 A", "0.33 A", "8 A"], answer: 0, explanation: "I = V/R = 12/4 = 3 A." },
      pp({ question: "Calculate the electrical energy used when a 240 V device draws 5 A for 30 s.", options: ["36,000 J", "1200 J", "36 J", "72,000 J"], answer: 0, explanation: "E = VIt = 240 × 5 × 30 = 36,000 J." }),
      pp({ question: "Three 6 Ω resistors are connected in series. What is the total resistance?", options: ["18 Ω", "2 Ω", "6 Ω", "9 Ω"], answer: 0, explanation: "Series: R = 6 + 6 + 6 = 18 Ω." }),
      pp({ question: "Two 4 Ω resistors are connected in parallel. What is the total resistance?", options: ["2 Ω", "8 Ω", "4 Ω", "1 Ω"], answer: 0, explanation: "Parallel: 1/R = 1/4 + 1/4 = 1/2, so R = 2 Ω." }),
      pp({ question: "A fuse in a plug is most likely rated at which value for a normal UK mains appliance?", options: ["3 A or 13 A", "100 A", "0.1 A", "1000 A"], answer: 0, explanation: "UK plug fuses are typically 3 A or 13 A depending on the appliance." }),
      pp({ question: "Which is a disadvantage of overhead power cables?", options: ["They use less material", "They are affected by weather and look unsightly", "They are underground", "They lose no energy"], answer: 1, explanation: "Overhead cables can be affected by weather and are visible." }),
      pp({ question: "A 12 V battery transfers 48 C of charge. How much energy is transferred?", options: ["576 J", "4 J", "60 J", "36 J"], answer: 0, explanation: "E = QV = 48 × 12 = 576 J." }),
    ],
  },
  {
    id: "ig-phy-waves",
    name: "Waves & Light",
    icon: "Zap",
    description: "Wave properties, reflection, refraction and the EM spectrum.",
    theory: "A wave transfers energy without transferring matter. Key terms: amplitude (maximum displacement from rest), wavelength (distance between two consecutive crests), frequency (number of waves per second, measured in Hz) and period (time for one wave). The wave equation is v = f × λ, where v is speed, f is frequency and λ is wavelength.\nReflection follows the law of reflection: the angle of incidence equals the angle of reflection, both measured from the normal (a line at 90° to the surface). Refraction is the bending of light when it passes from one medium to another due to a change in speed. When light enters a denser medium (e.g. air to glass) it bends towards the normal; when it leaves, it bends away. Total internal reflection occurs when the angle of incidence exceeds the critical angle, causing all light to reflect back inside.\nThe electromagnetic spectrum ranges from radio waves (longest wavelength, lowest frequency) through microwaves, infrared, visible light, ultraviolet, X-rays to gamma rays (shortest wavelength, highest frequency). All EM waves travel at 3 × 10⁸ m/s in a vacuum and can travel through a vacuum (unlike sound waves).",
    defaultTimeLimit: 30,
    questions: [
      { question: "What is the unit of frequency?", options: ["Hertz", "Metres", "Joules", "Watts"], answer: 0, explanation: "Frequency is measured in Hertz (Hz) — the number of waves per second.", timeLimit: 20 },
      { question: "The law of reflection states that the angle of incidence equals the angle of...", options: ["refraction", "reflection", "diffraction", "critical angle"], answer: 1, explanation: "The angle of incidence always equals the angle of reflection, both measured from the normal.", timeLimit: 25 },
      { question: "A wave has frequency 10 Hz and wavelength 3 m. Calculate its speed.", type: "written", options: [], answer: 0, acceptAnswers: ["30", "30 m/s", "30m/s"], explanation: "v = f × λ = 10 × 3 = 30 m/s.", timeLimit: 30 },
      { question: "Which type of wave can travel through a vacuum?", options: ["Sound waves", "Water waves", "Electromagnetic waves", "Seismic waves"], answer: 2, explanation: "EM waves (like light) don't need a medium and can travel through a vacuum.", timeLimit: 25 },
      { question: "When light enters glass from air, it bends ___ the normal.", options: ["towards", "away from", "parallel to", "perpendicular to"], answer: 0, explanation: "Light slows down in glass (denser medium), bending towards the normal.", timeLimit: 25 },
      pp({ question: "Light travels at 3 × 10⁸ m/s. Calculate the frequency of light with wavelength 6 × 10⁻⁷ m.", type: "written", options: [], answer: 0, acceptAnswers: ["5 × 10^14", "5 × 10¹⁴", "5x10^14", "5e14", "5 × 10¹⁴ Hz", "5 × 10^14 Hz"], explanation: "f = c / λ = (3 × 10⁸) / (6 × 10⁻⁷) = 5 × 10¹⁴ Hz.", timeLimit: 40 }),
      pp({ question: "Which has the longest wavelength in the electromagnetic spectrum?", options: ["Gamma rays", "Radio waves", "Visible light", "X-rays"], answer: 1, explanation: "Radio waves have the longest wavelength and lowest frequency in the EM spectrum.", timeLimit: 25 }),
      pp({ question: "Total internal reflection happens when the angle of incidence is ___ the critical angle.", options: ["less than", "equal to", "greater than", "perpendicular to"], answer: 2, explanation: "When the angle of incidence exceeds the critical angle, all light reflects back inside the denser medium.", timeLimit: 30 }),
      { question: "State the law of reflection in your own words.", type: "written", options: [], answer: 0, acceptAnswers: ["the angle of incidence equals the angle of reflection", "angle of incidence equals angle of reflection", "angle of incidence = angle of reflection", "the angle of incidence is equal to the angle of reflection"], explanation: "The law of reflection: the angle of incidence equals the angle of reflection (both measured from the normal).", timeLimit: 35 },
      { question: "Which colour of visible light has the highest frequency?", options: ["Red", "Green", "Violet", "Yellow"], answer: 2, explanation: "Violet has the shortest wavelength and highest frequency; red has the longest and lowest.", timeLimit: 25 },
    ],
  },
  {
    id: "ig-phy-thermal",
    name: "Thermal Physics",
    icon: "Flame",
    description: "Heat transfer, states of matter and specific heat capacity.",
    theory: "Heat can be transferred by three methods: conduction, convection and radiation. Conduction is the transfer of thermal energy through a material by vibrating particles passing energy to neighbours; metals are good conductors because of free electrons. Convection occurs in fluids (liquids and gases) when hot fluid expands, becomes less dense and rises, while cooler, denser fluid sinks — forming a convection current. Radiation is the transfer of heat by infrared waves, which can travel through a vacuum; dark, matte surfaces are good absorbers and emitters, while shiny, light surfaces are poor absorbers and good reflectors.\nIn solids, particles vibrate about fixed positions; in liquids, particles can move past each other; in gases, particles move freely and fast. During a change of state (melting, boiling), the temperature stays constant — the energy goes into breaking bonds (latent heat).\nSpecific heat capacity (c) is the energy needed to raise 1 kg of a substance by 1°C. The formula is E = m × c × ΔT, where E is energy in joules, m is mass in kg, c is specific heat capacity in J/(kg·°C), and ΔT is the temperature change in °C.",
    defaultTimeLimit: 35,
    questions: [
      { question: "Which method of heat transfer can travel through a vacuum?", options: ["Conduction", "Convection", "Radiation", "Evaporation"], answer: 2, explanation: "Radiation (infrared) is the only method that can travel through a vacuum — it doesn't need a medium.", timeLimit: 25 },
      { question: "In convection, hot fluid...", options: ["sinks because it is denser", "rises because it is less dense", "stays still", "moves sideways"], answer: 1, explanation: "Hot fluid expands, becomes less dense and rises; cooler, denser fluid sinks.", timeLimit: 25 },
      { question: "Calculate the energy needed to heat 2 kg of water by 10°C. (c = 4200 J/kg·°C)", type: "written", options: [], answer: 0, acceptAnswers: ["84000", "84000 J", "84000J", "84,000 J", "84,000"], explanation: "E = mcΔT = 2 × 4200 × 10 = 84,000 J.", timeLimit: 40 },
      { question: "Which is the best conductor of heat?", options: ["Wood", "Plastic", "Copper", "Air"], answer: 2, explanation: "Copper is a metal with free electrons — an excellent conductor. Wood, plastic and air are insulators.", timeLimit: 25 },
      pp({ question: "A 0.5 kg block of iron (c = 460 J/kg·°C) is heated from 20°C to 40°C. Calculate the energy supplied.", type: "written", options: [], answer: 0, acceptAnswers: ["4600", "4600 J", "4600J"], explanation: "E = mcΔT = 0.5 × 460 × (40 − 20) = 0.5 × 460 × 20 = 4600 J.", timeLimit: 40 }),
      pp({ question: "Dark, matte surfaces are ___ absorbers of infrared radiation.", options: ["poor", "good", "transparent", "reflective"], answer: 1, explanation: "Dark, matte surfaces are good absorbers and emitters of infrared; shiny light surfaces are poor absorbers.", timeLimit: 25 }),
      pp({ question: "During evaporation, the temperature of the remaining liquid...", options: ["increases", "stays the same", "decreases", "fluctuates randomly"], answer: 2, explanation: "The fastest particles escape during evaporation, so the average kinetic energy of the remaining liquid drops — it cools.", timeLimit: 30 }),
      { question: "State the three methods of heat transfer.", type: "written", options: [], answer: 0, acceptAnswers: ["conduction, convection, radiation", "conduction convection radiation", "convection, conduction, radiation", "conduction convection and radiation", "conduction, convection and radiation"], explanation: "The three methods are conduction, convection and radiation.", timeLimit: 35 },
      { question: "Latent heat is the energy needed to change state at constant...", options: ["volume", "pressure", "temperature", "mass"], answer: 2, explanation: "During a change of state the temperature stays constant; the energy (latent heat) goes into breaking intermolecular bonds.", timeLimit: 30 },
      { question: "Which happens when a solid melts?", options: ["Particles slow down completely", "Particles gain energy and break free from fixed positions", "Particles lose energy", "The substance disappears"], answer: 1, explanation: "As a solid is heated, particles gain enough energy to break their fixed positions and become a liquid.", timeLimit: 25 },
    ],
  },
];

/* ===================== CHEMISTRY (ELECTIVE) ===================== */
const IGCSE_CHEMISTRY_TOPICS: Topic[] = [
  {
    id: "ig-chem-atomic",
    name: "Atomic Structure",
    icon: "Atom",
    description: "Atoms, elements, compounds and the Periodic Table.",
    questions: [
      { question: "What is the atomic number of an element?", options: ["Number of neutrons", "Number of protons", "Mass of the atom", "Number of molecules"], answer: 1, explanation: "Atomic number = number of protons." },
      { question: "Which subatomic particle has no charge?", options: ["Proton", "Neutron", "Electron", "Ion"], answer: 1, explanation: "Neutrons have no charge (neutral)." },
      { question: "An atom has 11 protons and 12 neutrons. What is its mass number?", options: ["11", "12", "23", "1"], answer: 2, explanation: "Mass number = protons + neutrons = 11 + 12 = 23." },
      { question: "Which is a noble gas?", options: ["Oxygen", "Sodium", "Neon", "Iron"], answer: 2, explanation: "Neon is a noble gas (Group 0/18)." },
      pp({ question: "An atom has 6 protons, 6 neutrons and 6 electrons. What is it?", options: ["Carbon-12", "Oxygen", "Nitrogen-12", "Lithium"], answer: 0, explanation: "6 protons = carbon; mass 12 = Carbon-12." }),
      pp({ question: "What is the electronic configuration of sodium (atomic number 11)?", options: ["2,8,1", "2,9", "1,8,2", "11"], answer: 0, explanation: "2, 8, 1 — filling shells in order." }),
      pp({ question: "Which group of the Periodic Table contains the most reactive non-metals?", options: ["Group 1", "Group 0", "Group 7 (halogens)", "Group 2"], answer: 2, explanation: "Group 7 (halogens) are the most reactive non-metals." }),
      pp({ question: "Isotopes of an element have the same number of ___ but different numbers of ___.", options: ["protons; electrons", "protons; neutrons", "neutrons; protons", "electrons; protons"], answer: 1, explanation: "Isotopes have the same protons (same element) but different neutrons." }),
      pp({ question: "Which is a compound?", options: ["O₂", "Na", "HCl", "Fe"], answer: 2, explanation: "HCl has two different elements bonded — a compound." }),
      pp({ question: "Why are Group 1 metals very reactive?", options: ["They have 8 outer electrons", "They have 1 outer electron they lose easily", "They have full shells", "They are gases"], answer: 1, explanation: "Group 1 metals have 1 outer electron they lose easily to form +1 ions." }),
    ],
  },
  {
    id: "ig-chem-reactions",
    name: "Chemical Reactions",
    icon: "FlaskConical",
    description: "Equations, acids, bases and rates of reaction.",
    questions: [
      { question: "What is the pH of a neutral solution?", options: ["0", "7", "14", "1"], answer: 1, explanation: "Neutral pH = 7." },
      { question: "What type of salt does nitric acid (HNO₃) form?", options: ["Chloride", "Nitrate", "Sulfate", "Ethanoate"], answer: 1, explanation: "Nitric acid forms nitrates." },
      { question: "What gas is produced when a metal reacts with an acid?", options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], answer: 2, explanation: "Metal + acid → salt + hydrogen." },
      { question: "Which is a base (alkali)?", options: ["HCl", "NaOH", "HNO₃", "H₂SO₄"], answer: 1, explanation: "NaOH (sodium hydroxide) is a base." },
      pp({ question: "Balance the equation: ___H₂ + O₂ → ___H₂O. What coefficients balance it?", options: ["1, 1", "2, 2", "2, 1", "1, 2"], answer: 1, explanation: "2H₂ + O₂ → 2H₂O. Two H₂ molecules and two H₂O molecules balance it." }),
      pp({ question: "When magnesium carbonate is heated, it decomposes. What solid is left?", options: ["Magnesium oxide", "Magnesium metal", "Magnesium hydroxide", "Magnesium chloride"], answer: 0, explanation: "MgCO₃ → MgO + CO₂. The solid left is magnesium oxide." }),
      pp({ question: "Which increases the rate of a reaction?", options: ["Lower temperature", "Smaller surface area", "Higher concentration", "Larger pieces"], answer: 2, explanation: "Higher concentration = more frequent collisions = faster reaction." }),
      pp({ question: "What is oxidation?", options: ["Gain of electrons", "Loss of electrons", "Gain of neutrons", "Loss of protons"], answer: 1, explanation: "Oxidation = loss of electrons (OIL RIG)." }),
      pp({ question: "A catalyst speeds up a reaction by...", options: ["Increasing temperature", "Lowering the activation energy", "Being used up", "Adding more reactant"], answer: 1, explanation: "A catalyst lowers activation energy; it's not used up." }),
      pp({ question: "What is the test for carbon dioxide?", options: ["Glowing splint relights", "Limewater turns milky", "Pop with a lit splint", "Burns with a squeaky pop"], answer: 1, explanation: "CO₂ turns limewater milky." }),
    ],
  },
  {
    id: "ig-chem-organic",
    name: "Organic Chemistry",
    icon: "FlaskConical",
    description: "Hydrocarbons, alkanes, alkenes, crude oil and polymers.",
    theory: "Organic chemistry is the study of carbon-containing compounds. Hydrocarbons are compounds of carbon and hydrogen only. The main families are alkanes (saturated, single bonds, general formula CₙH₂ₙ₊₂) and alkenes (unsaturated, contain a C=C double bond, general formula CₙH₂ₙ). The first four alkanes are methane (CH₄), ethane (C₂H₆), propane (C₃H₈) and butane (C₄H₁₀). The first alkenes are ethene (C₂H₄) and propene (C₃H₆).\nCrude oil is a mixture of hydrocarbons formed from ancient biomass. It is separated by fractional distillation: the oil is heated and vapours rise through a column that gets cooler towards the top. Shorter-chain fractions (lower boiling points, more volatile) condense near the top; longer-chain fractions (higher boiling points) condense lower down.\nAlkenes are unsaturated — they decolourise bromine water (orange to colourless). This is a test for a C=C double bond. Alkenes undergo addition reactions and addition polymerisation, where many small monomer molecules join to form a large polymer. Complete combustion of any hydrocarbon produces carbon dioxide and water.",
    defaultTimeLimit: 30,
    questions: [
      { question: "What is the general formula of alkanes?", options: ["CₙH₂ₙ", "CₙH₂ₙ₊₂", "CₙHₙ", "CₙH₂ₙ₋₂"], answer: 1, explanation: "Alkanes are saturated: general formula CₙH₂ₙ₊₂.", timeLimit: 25 },
      { question: "Which is the simplest alkane?", options: ["Ethane", "Methane (CH₄)", "Propane", "Butane"], answer: 1, explanation: "Methane (CH₄) is the smallest alkane — one carbon, four hydrogens.", timeLimit: 20 },
      { question: "What is the molecular formula of ethene?", type: "written", options: [], answer: 0, acceptAnswers: ["C2H4", "C₂H₄", "C2H4", "C2H4"], explanation: "Ethene has 2 carbons and a double bond: C₂H₄.", timeLimit: 25 },
      { question: "Alkenes are described as ___ because they contain a C=C double bond.", options: ["saturated", "unsaturated", "inert", "ionic"], answer: 1, explanation: "Alkenes are unsaturated — the C=C bond allows them to undergo addition reactions.", timeLimit: 25 },
      pp({ question: "How many carbon atoms are in propane?", type: "written", options: [], answer: 0, acceptAnswers: ["3"], explanation: "Propane has 3 carbons (C₃H₈) — 'prop' = 3.", timeLimit: 20 }),
      pp({ question: "In fractional distillation of crude oil, which fraction is collected at the top of the column?", options: ["Bitumen (longest chains)", "Diesel", "The fraction with the lowest boiling point", "Kerosene"], answer: 2, explanation: "The top of the column is coolest, so the most volatile (lowest boiling point) fractions condense there.", timeLimit: 30 }),
      pp({ question: "The test for an alkene uses ___ and turns it from orange to colourless.", options: ["limewater", "bromine water", "litmus solution", "universal indicator"], answer: 1, explanation: "Bromine water decolourises (orange → colourless) when it adds across the C=C double bond of an alkene.", timeLimit: 25 }),
      { question: "What type of bond holds carbon and hydrogen together in alkanes?", options: ["Ionic", "Covalent", "Metallic", "Hydrogen bonds"], answer: 1, explanation: "C–H bonds are covalent — electrons are shared between atoms.", timeLimit: 25 },
      { question: "What is the name of the process that joins many small alkene molecules into a large polymer?", type: "written", options: [], answer: 0, acceptAnswers: ["polymerisation", "addition polymerisation", "polymerization", "addition polymerization"], explanation: "Addition polymerisation joins many alkene monomers to form a long polymer chain.", timeLimit: 30 },
      { question: "Complete combustion of a hydrocarbon produces...", options: ["carbon monoxide and water", "carbon dioxide and water", "carbon and hydrogen", "methane and oxygen"], answer: 1, explanation: "In plenty of oxygen: hydrocarbon + O₂ → CO₂ + H₂O.", timeLimit: 25 },
    ],
  },
  {
    id: "ig-chem-quantitative",
    name: "Quantitative Chemistry",
    icon: "Atom",
    description: "Moles, molar mass, concentration, titrations and reacting masses.",
    theory: "The mole is the unit for amount of substance. One mole contains 6 × 10²³ particles (the Avogadro constant). The number of moles = mass (g) ÷ molar mass (g/mol). The molar mass (Mr) is the sum of the atomic masses of all atoms in the formula. For example, Mr of CO₂ = 12 + (2 × 16) = 44 g/mol.\nConcentration measures how much solute is dissolved in a given volume. Concentration (mol/dm³) = moles ÷ volume (dm³). Remember: 1 dm³ = 1000 cm³, so divide cm³ by 1000 to get dm³.\nTitrations are used to find the exact volume of one solution that reacts with a known volume of another. The solution of known concentration is placed in the burette and the unknown in the flask. An indicator shows the end-point. The limiting reactant is the reactant that is completely used up first, determining how much product forms. When balancing reacting masses, use the mole ratio from the balanced equation.",
    defaultTimeLimit: 40,
    questions: [
      { question: "What is the approximate value of the Avogadro constant?", options: ["6 × 10²³", "6 × 10²²", "6 × 10²⁴", "3 × 10⁸"], answer: 0, explanation: "The Avogadro constant is approximately 6 × 10²³ particles per mole.", timeLimit: 25 },
      { question: "Calculate the number of moles in 36 g of water (H₂O, Mr = 18).", type: "written", options: [], answer: 0, acceptAnswers: ["2", "2 mol", "2 moles"], explanation: "Moles = mass / Mr = 36 / 18 = 2 mol.", timeLimit: 30 },
      { question: "What is the molar mass of CO₂? (C = 12, O = 16)", options: ["28 g/mol", "32 g/mol", "44 g/mol", "48 g/mol"], answer: 2, explanation: "Mr = 12 + (2 × 16) = 44 g/mol.", timeLimit: 30 },
      { question: "Calculate the concentration of a solution containing 0.5 moles in 250 cm³. Give your answer in mol/dm³.", type: "written", options: [], answer: 0, acceptAnswers: ["2", "2 mol/dm3", "2 mol/dm³", "2mol/dm3", "2 mol dm-3"], explanation: "250 cm³ = 0.25 dm³. Concentration = 0.5 / 0.25 = 2 mol/dm³.", timeLimit: 40 },
      pp({ question: "Calculate the mass of 0.5 moles of NaOH (Mr = 40).", type: "written", options: [], answer: 0, acceptAnswers: ["20", "20 g", "20g"], explanation: "Mass = moles × Mr = 0.5 × 40 = 20 g.", timeLimit: 35 }),
      pp({ question: "In a titration, the solution of known concentration is placed in the...", options: ["conical flask", "burette", "beaker", "pipette only"], answer: 1, explanation: "The solution of known concentration goes in the burette; the unknown is measured into the flask with a pipette.", timeLimit: 30 }),
      pp({ question: "What is the concentration if 0.2 mol of solute is dissolved in 500 cm³ of solution?", options: ["0.1 mol/dm³", "0.2 mol/dm³", "0.4 mol/dm³", "100 mol/dm³"], answer: 2, explanation: "500 cm³ = 0.5 dm³. Concentration = 0.2 / 0.5 = 0.4 mol/dm³.", timeLimit: 40 }),
      { question: "The limiting reactant is the one that...", options: ["is left over at the end", "is completely used up first", "has the largest mass", "is a catalyst"], answer: 1, explanation: "The limiting reactant is consumed first and limits how much product can form.", timeLimit: 25 },
      { question: "How many moles of CO₂ are produced when 2 moles of CH₄ burn completely? (CH₄ + 2O₂ → CO₂ + 2H₂O)", type: "written", options: [], answer: 0, acceptAnswers: ["2", "2 mol", "2 moles"], explanation: "The mole ratio is 1:1 for CH₄:CO₂, so 2 moles of CH₄ produce 2 moles of CO₂.", timeLimit: 35 },
      { question: "What is the mass of 3 moles of CaCO₃? (Ca = 40, C = 12, O = 16)", options: ["100 g", "150 g", "300 g", "500 g"], answer: 2, explanation: "Mr = 40 + 12 + (3 × 16) = 100. Mass = 3 × 100 = 300 g.", timeLimit: 35 },
    ],
  },
];

/* ===================== BIOLOGY (ELECTIVE) ===================== */
const IGCSE_BIOLOGY_TOPICS: Topic[] = [
  {
    id: "ig-bio-cells",
    name: "Cells & Organisms",
    icon: "Microscope",
    description: "Cell structure, transport and organisation.",
    questions: [
      { question: "Which part of the cell controls its activities?", options: ["Cell membrane", "Nucleus", "Cytoplasm", "Cell wall"], answer: 1, explanation: "The nucleus controls the cell." },
      { question: "What is the function of the cell membrane?", options: ["Stores water", "Controls what enters and leaves", "Makes protein", "Provides energy"], answer: 1, explanation: "The cell membrane controls entry and exit of substances." },
      { question: "Which organelle is the site of photosynthesis?", options: ["Nucleus", "Mitochondria", "Chloroplast", "Ribosome"], answer: 2, explanation: "Chloroplasts contain chlorophyll and are where photosynthesis happens." },
      { question: "What process moves water across a partially permeable membrane?", options: ["Diffusion", "Osmosis", "Active transport", "Evaporation"], answer: 1, explanation: "Osmosis is the movement of water across a partially permeable membrane." },
      pp({ question: "Which is found in plant cells but NOT animal cells?", options: ["Nucleus", "Cell membrane", "Cell wall", "Mitochondria"], answer: 2, explanation: "Plant cells have a cell wall; animal cells do not." }),
      pp({ question: "What is the function of mitochondria?", options: ["Photosynthesis", "Respiration (releasing energy)", "Storing water", "Controlling the cell"], answer: 1, explanation: "Mitochondria are the site of aerobic respiration." }),
      pp({ question: "Diffusion is the movement of particles from...", options: ["Low to high concentration", "High to low concentration (down a gradient)", "Against a concentration gradient", "Only through membranes"], answer: 1, explanation: "Diffusion is net movement from high to low concentration." }),
      pp({ question: "A group of similar cells working together is called a...", options: ["Organ", "Organ system", "Tissue", "Organism"], answer: 2, explanation: "A tissue is a group of similar cells doing the same job." }),
      pp({ question: "Which is the correct order from smallest to largest?", options: ["Organ → Tissue → Cell → Organism", "Cell → Tissue → Organ → Organism", "Cell → Organ → Tissue → Organism", "Tissue → Cell → Organ → Organism"], answer: 1, explanation: "Cell → tissue → organ → organ system → organism." }),
      pp({ question: "Why do root hair cells have a large surface area?", options: ["To look nice", "To absorb water and minerals efficiently", "To store food", "To photosynthesise"], answer: 1, explanation: "Large surface area allows faster absorption of water and mineral ions." }),
    ],
  },
  {
    id: "ig-bio-ecosystems",
    name: "Ecosystems & Cycles",
    icon: "Leaf",
    description: "Food chains, nutrient cycles and human impact.",
    questions: [
      { question: "What do we call organisms that make their own food?", options: ["Consumers", "Producers", "Decomposers", "Predators"], answer: 1, explanation: "Producers (plants) make their own food by photosynthesis." },
      { question: "Which process removes carbon dioxide from the atmosphere?", options: ["Respiration", "Combustion", "Photosynthesis", "Decomposition"], answer: 2, explanation: "Photosynthesis removes CO₂; respiration and combustion add it." },
      { question: "What is a decomposer?", options: ["A plant", "An organism that breaks down dead matter", "A predator", "A producer"], answer: 1, explanation: "Decomposers (e.g. fungi, bacteria) break down dead organisms." },
      { question: "In a food chain, energy ___ at each step.", options: ["Increases", "Stays the same", "Decreases", "Doubles"], answer: 2, explanation: "Energy is lost at each trophic level (mostly as heat)." },
      pp({ question: "In the carbon cycle, what process releases carbon dioxide back into the air?", options: ["Photosynthesis only", "Respiration and combustion", "Only decomposition", "Transpiration"], answer: 1, explanation: "Respiration and combustion release CO₂." }),
      pp({ question: "Why are there usually fewer top predators than producers in an ecosystem?", options: ["Predators eat more", "Energy is lost at each trophic level", "Predators are bigger", "There is less water"], answer: 1, explanation: "Only about 10% of energy passes to the next level, so top predators are fewer." }),
      pp({ question: "Which is an abiotic factor?", options: ["Plants", "Bacteria", "Temperature", "Animals"], answer: 2, explanation: "Abiotic = non-living; temperature is non-living." }),
      pp({ question: "What is eutrophication caused by?", options: ["Too little oxygen", "Excess nitrates from fertilisers entering water", "Deforestation", "Overfishing"], answer: 1, explanation: "Excess nitrates cause algae blooms; decay then removes oxygen." }),
      pp({ question: "Which process converts nitrogen gas into nitrates in soil?", options: ["Respiration", "Nitrogen fixation", "Combustion", "Photosynthesis"], answer: 1, explanation: "Nitrogen fixation (by bacteria) converts N₂ into usable nitrates." }),
      pp({ question: "Biomagnification means toxins...", options: ["Disappear in food chains", "Become more concentrated higher up the food chain", "Only affect plants", "Are harmless to predators"], answer: 1, explanation: "Toxins build up in concentration along a food chain." }),
    ],
  },
  {
    id: "ig-bio-human",
    name: "Human Body Systems",
    icon: "Leaf",
    description: "Digestion, respiration, circulation, nerves and excretion.",
    theory: "The human body is made up of several organ systems that work together. The digestive system breaks down food into small molecules that can be absorbed. Food is chewed in the mouth (amylase starts starch digestion), churned in the stomach with acid and protease, and most absorption happens in the small intestine (lined with villi for a large surface area). The liver produces bile which emulsifies fats.\nThe respiratory system exchanges gases. Air enters via the trachea, bronchi and bronchioles into the alveoli, where oxygen diffuses into the blood and carbon dioxide diffuses out. Aerobic respiration uses oxygen: glucose + oxygen → carbon dioxide + water + energy (ATP).\nThe circulatory system pumps blood around the body. The heart has four chambers (right and left atria, right and left ventricles). Arteries carry blood away from the heart, veins carry it back, and capillaries exchange substances with cells. The nervous system carries electrical impulses along neurones; a reflex arc is a fast, automatic response that does not involve the brain. The kidneys are the main organs of excretion, removing urea and excess water as urine.",
    defaultTimeLimit: 30,
    questions: [
      { question: "Where in the digestive system does most absorption of nutrients occur?", options: ["Stomach", "Small intestine", "Large intestine", "Mouth"], answer: 1, explanation: "The small intestine is lined with villi, giving a large surface area for absorption.", timeLimit: 25 },
      { question: "What is the role of bile in digestion?", options: ["It digests protein", "It emulsifies fats", "It absorbs water", "It kills bacteria"], answer: 1, explanation: "Bile (made in the liver) emulsifies fats into smaller droplets, increasing surface area for lipase.", timeLimit: 25 },
      { question: "Write the word equation for aerobic respiration.", type: "written", options: [], answer: 0, acceptAnswers: ["glucose + oxygen -> carbon dioxide + water + energy", "glucose + oxygen = carbon dioxide + water + energy", "glucose + oxygen → carbon dioxide + water + energy", "glucose+oxygen→carbon dioxide+water+energy"], explanation: "Aerobic respiration: glucose + oxygen → carbon dioxide + water + energy (ATP).", timeLimit: 35 },
      { question: "Which blood vessels carry blood away from the heart?", options: ["Veins", "Arteries", "Capillaries", "Valves"], answer: 1, explanation: "Arteries carry blood away from the heart (usually oxygenated); veins carry it back.", timeLimit: 25 },
      pp({ question: "How many chambers does the human heart have?", type: "written", options: [], answer: 0, acceptAnswers: ["4", "four"], explanation: "The heart has four chambers: left & right atria, left & right ventricles.", timeLimit: 20 }),
      pp({ question: "Where does gas exchange happen in the lungs?", options: ["Trachea", "Bronchi", "Alveoli", "Diaphragm"], answer: 2, explanation: "Gas exchange happens in the alveoli — their thin walls and large surface area allow O₂ in and CO₂ out.", timeLimit: 25 }),
      pp({ question: "A reflex arc is a response that...", options: ["is slow and conscious", "is fast and automatic (no brain involvement)", "only happens in plants", "involves hormones only"], answer: 1, explanation: "A reflex is a fast, automatic response that passes through the spinal cord, not the brain.", timeLimit: 30 }),
      { question: "Which organ is the main organ of excretion in humans?", options: ["Liver", "Kidneys", "Lungs", "Skin"], answer: 1, explanation: "The kidneys filter the blood and excrete urea and excess water as urine.", timeLimit: 25 },
      { question: "What substance is excreted by the kidneys?", type: "written", options: [], answer: 0, acceptAnswers: ["urea", "urine"], explanation: "The kidneys excrete urea (a waste product from the breakdown of proteins) in urine.", timeLimit: 25 },
      { question: "What feature of the small intestine increases absorption?", options: ["Thick walls", "Villi (finger-like projections)", "No blood supply", "Acidic pH"], answer: 1, explanation: "Villi and microvilli give the small intestine a huge surface area for absorbing digested food.", timeLimit: 25 },
    ],
  },
  {
    id: "ig-bio-genetics",
    name: "Genetics & Inheritance",
    icon: "Dna",
    description: "DNA, genes, chromosomes, inheritance, variation and evolution.",
    theory: "DNA is the molecule of inheritance. It is a double helix made of two strands linked by bases (A–T and C–G). A gene is a section of DNA that codes for a specific protein. Genes are carried on chromosomes — humans have 23 pairs (46 total), with the 23rd pair determining sex (XX female, XY male).\nAlleles are different versions of a gene. A dominant allele shows its effect even with one copy (represented by a capital letter); a recessive allele only shows with two copies (lower case). Your genotype is the alleles you carry; your phenotype is the physical characteristic you show. A Punnett square predicts the probability of offspring genotypes.\nVariation between individuals can be genetic (inherited), environmental (caused by surroundings) or a combination. Evolution is the gradual change in species over time, mainly by natural selection: individuals with advantageous traits are more likely to survive and reproduce, passing those traits on.",
    defaultTimeLimit: 35,
    questions: [
      { question: "What shape is the DNA molecule?", options: ["Single strand", "Double helix", "Circle", "Triangle"], answer: 1, explanation: "DNA is a double helix — two strands twisted together.", timeLimit: 20 },
      { question: "How many pairs of chromosomes does a normal human cell contain?", options: ["23 pairs", "46 pairs", "2 pairs", "92 pairs"], answer: 0, explanation: "Humans have 23 pairs (46 total) of chromosomes in each body cell.", timeLimit: 25 },
      { question: "Which sex chromosomes does a biological female have?", type: "written", options: [], answer: 0, acceptAnswers: ["XX", "xx", "X X"], explanation: "Females have two X chromosomes (XX); males have XY.", timeLimit: 25 },
      { question: "A dominant allele is represented by...", options: ["a lowercase letter", "a capital letter", "a number", "a symbol"], answer: 1, explanation: "Dominant alleles are written with a capital letter (e.g. B); recessive with lowercase (b).", timeLimit: 25 },
      pp({ question: "In a cross Bb × Bb (B dominant), what fraction of offspring show the recessive phenotype?", options: ["1/4", "1/2", "3/4", "All"], answer: 0, explanation: "Punnett square gives BB, Bb, Bb, bb — only bb (1 in 4) shows the recessive phenotype.", timeLimit: 35 }),
      pp({ question: "Natural selection means individuals with ___ traits are more likely to survive and reproduce.", options: ["disadvantageous", "advantageous", "no", "recessive"], answer: 1, explanation: "Advantageous traits increase survival and reproduction, so they are passed on more often.", timeLimit: 30 }),
      pp({ question: "The physical characteristic shown by an organism is its...", options: ["genotype", "phenotype", "karyotype", "allele"], answer: 1, explanation: "Phenotype = the observable characteristic; genotype = the alleles carried.", timeLimit: 25 }),
      { question: "Which base pairs with adenine (A) in DNA?", options: ["Guanine", "Thymine", "Cytosine", "Uracil"], answer: 1, explanation: "A pairs with T (adenine–thymine); C pairs with G (cytosine–guanine).", timeLimit: 25 },
      { question: "Name one source of variation in a population.", type: "written", options: [], answer: 0, acceptAnswers: ["genetic", "environmental", "mutation", "inherited", "genes", "diet", "environment"], explanation: "Variation comes from genetic (inheritance, mutation) and environmental (diet, surroundings) factors.", timeLimit: 30 },
      { question: "A change in the DNA sequence is called a...", options: ["mutation", "phenotype", "allele", "chromosome"], answer: 0, explanation: "A mutation is a random change in the DNA sequence, which can create new alleles.", timeLimit: 25 },
    ],
  },
];

/* ===================== ECONOMICS (ELECTIVE) ===================== */
const IGCSE_ECONOMICS_TOPICS: Topic[] = [
  {
    id: "ig-econ-basics",
    name: "Economic Basics",
    icon: "TrendingUp",
    description: "Scarcity, choice and opportunity cost.",
    questions: [
      { question: "What is the basic economic problem?", options: ["Too much money", "Limited resources, unlimited wants (scarcity)", "No demand", "Too many workers"], answer: 1, explanation: "Scarcity — resources are limited but wants are unlimited." },
      { question: "Opportunity cost is...", options: ["The money paid for a good", "The next best alternative given up", "Total cost of production", "A type of tax"], answer: 1, explanation: "Opportunity cost = the next best alternative foregone." },
      { question: "Which is a factor of production?", options: ["Money", "Land", "Profit", "Shares"], answer: 1, explanation: "Factors of production: land, labour, capital, enterprise." },
      { question: "What type of good is a public park?", options: ["Private good", "Public good", "Inferior good", "Luxury good"], answer: 1, explanation: "A public good is non-excludable and non-rivalrous." },
      pp({ question: "A country produces only guns and butter. Producing more guns means less butter. This shows...", options: ["Demand", "Opportunity cost", "Profit", "Inflation"], answer: 1, explanation: "The trade-off is the opportunity cost." }),
      pp({ question: "Which is a mixed economy?", options: ["One with only private firms", "One with both private and government activity", "One with no government", "One with only state firms"], answer: 1, explanation: "A mixed economy has both private and public sectors." }),
      pp({ question: "Labour as a factor of production refers to...", options: ["Machines", "Human effort/work", "Land", "Money"], answer: 1, explanation: "Labour = human work effort." }),
      pp({ question: "If a farmer chooses to grow wheat instead of maize, the opportunity cost is...", options: ["The wheat", "The maize they could have grown", "The money spent", "Zero"], answer: 1, explanation: "Opportunity cost = the maize given up." }),
      pp({ question: "Which is an example of capital (factor of production)?", options: ["A farmer", "A tractor", "A field", "Profit"], answer: 1, explanation: "Capital = man-made goods used to produce, e.g. a tractor." }),
      pp({ question: "Scarcity means that choices must be made because...", options: ["Resources are unlimited", "Resources are limited but wants are unlimited", "Nobody wants anything", "Governments decide everything"], answer: 1, explanation: "Scarcity forces choice between competing uses of limited resources." }),
    ],
  },
  {
    id: "ig-econ-demand-supply",
    name: "Demand & Supply",
    icon: "TrendingUp",
    description: "Demand and supply curves, equilibrium, shifts and price mechanism.",
    theory: "Demand is the quantity of a good that consumers are willing and able to buy at each price. The law of demand states that as price rises, quantity demanded falls (a downward-sloping curve). Supply is the quantity producers are willing and able to sell at each price; the law of supply states that as price rises, quantity supplied rises (an upward-sloping curve).\nMarket equilibrium is where the demand and supply curves meet — at this price, the quantity demanded equals the quantity supplied, so there is no shortage or surplus. If price is above equilibrium there is excess supply (surplus); if below, excess demand (shortage).\nA shift of the demand curve (not a movement along it) is caused by changes in income, tastes, the price of related goods (substitutes and complements) or expectations. A shift of the supply curve is caused by changes in costs of production, technology, taxes/subsidies or weather. The price mechanism allocates resources: prices act as signals and incentives, rationing scarce goods and rewarding producers.",
    defaultTimeLimit: 35,
    questions: [
      { question: "The law of demand states that as price rises, quantity demanded...", options: ["rises", "falls", "stays the same", "doubles"], answer: 1, explanation: "As price rises, fewer consumers are willing/able to buy, so quantity demanded falls.", timeLimit: 25 },
      { question: "The law of supply states that as price rises, quantity supplied...", options: ["falls", "rises", "stays the same", "drops to zero"], answer: 1, explanation: "Higher prices give producers more incentive to supply, so quantity supplied rises.", timeLimit: 25 },
      { question: "Market equilibrium is the price where...", type: "written", options: [], answer: 0, acceptAnswers: ["quantity demanded equals quantity supplied", "demand equals supply", "quantity demanded = quantity supplied", "supply equals demand", "quantity supplied equals quantity demanded"], explanation: "At equilibrium, quantity demanded = quantity supplied — there is no shortage or surplus.", timeLimit: 30 },
      { question: "If price is set above equilibrium, there will be...", options: ["excess demand (shortage)", "excess supply (surplus)", "equilibrium", "no effect"], answer: 1, explanation: "Above equilibrium price, quantity supplied exceeds quantity demanded, creating a surplus.", timeLimit: 30 },
      pp({ question: "A substitute good is one that...", options: ["is used together with another good", "can be used in place of another good", "is always cheaper", "has no demand"], answer: 1, explanation: "A substitute can replace another good (e.g. tea for coffee); if coffee's price rises, tea demand rises.", timeLimit: 30 }),
      pp({ question: "A fall in the cost of production will shift the supply curve to the...", options: ["left", "right", "up only", "not at all"], answer: 1, explanation: "Lower costs mean producers supply more at each price — the curve shifts right (increase in supply).", timeLimit: 30 }),
      pp({ question: "Complementary goods are goods that...", options: ["compete with each other", "are used together", "are the same", "are never bought"], answer: 1, explanation: "Complements are used together (e.g. cars and petrol); if one's price rises, demand for the other falls.", timeLimit: 30 }),
      { question: "A rise in consumer income shifts the demand curve for a normal good to the...", options: ["left", "right", "down only", "no shift"], answer: 1, explanation: "More income means more demand at each price for a normal good — the curve shifts right.", timeLimit: 30 },
      { question: "The price mechanism means prices act as ___ and incentives to allocate resources.", type: "written", options: [], answer: 0, acceptAnswers: ["signals", "signal"], explanation: "Prices act as signals (showing where demand is) and incentives (encouraging producers to supply what people want).", timeLimit: 30 },
      { question: "If the price of a good is below equilibrium, the most likely result is a...", options: ["surplus", "shortage", "stable price", "higher supply"], answer: 1, explanation: "Below equilibrium, quantity demanded exceeds quantity supplied, causing a shortage.", timeLimit: 25 },
    ],
  },
];

/* ===================== ICT (ELECTIVE) ===================== */
const IGCSE_ICT_TOPICS: Topic[] = [
  {
    id: "ig-ict-basics",
    name: "ICT Fundamentals",
    icon: "Cpu",
    description: "Hardware, software, networks and data.",
    questions: [
      { question: "Which is hardware?", options: ["A word processor", "A keyboard", "An operating system", "A web browser"], answer: 1, explanation: "Hardware = physical parts; a keyboard is hardware." },
      { question: "Which is system software?", options: ["A spreadsheet", "An operating system", "A game", "A photo editor"], answer: 1, explanation: "An operating system is system software." },
      { question: "What does RAM stand for?", options: ["Read Access Memory", "Random Access Memory", "Rapid Access Module", "Random Application Memory"], answer: 1, explanation: "RAM = Random Access Memory." },
      { question: "Which is an input device?", options: ["Monitor", "Printer", "Keyboard", "Speaker"], answer: 2, explanation: "A keyboard is an input device." },
      pp({ question: "Which is the smallest unit of data?", options: ["Byte", "Bit", "Kilobyte", "Megabyte"], answer: 1, explanation: "A bit (0 or 1) is the smallest unit." }),
      pp({ question: "How many bits are in a byte?", options: ["4", "8", "16", "1000"], answer: 1, explanation: "1 byte = 8 bits." }),
      pp({ question: "Which is an output device?", options: ["Mouse", "Keyboard", "Monitor", "Microphone"], answer: 2, explanation: "A monitor outputs information to the user." }),
      pp({ question: "What does LAN stand for?", options: ["Local Area Network", "Large Access Node", "Long Array Network", "Local Application Net"], answer: 0, explanation: "LAN = Local Area Network." }),
      pp({ question: "Which is a type of malware?", options: ["Firewall", "Virus", "Router", "Browser"], answer: 1, explanation: "A virus is a type of malware." }),
      pp({ question: "Which is an example of secondary storage?", options: ["RAM", "ROM", "Hard drive", "Cache"], answer: 2, explanation: "A hard drive is secondary storage (non-volatile)." }),
    ],
  },
  {
    id: "ig-ict-networks",
    name: "Networks & Security",
    icon: "Cpu",
    description: "Networks, internet, protocols, cybersecurity and encryption.",
    theory: "A network is two or more computers connected together to share data and resources. A LAN (Local Area Network) covers a small area like a school; a WAN (Wide Area Network) spans a large geographical area. The internet is a global network of networks. Data is broken into packets and sent across networks — each packet carries the destination address.\nProtocols are agreed rules for communication. Key protocols include TCP/IP (transmission and addressing), HTTP/HTTPS (web pages), FTP (file transfer) and SMTP (email). An IP address uniquely identifies a device on a network; DNS (Domain Name System) translates human-readable domain names into IP addresses.\nCybersecurity protects systems, software and data from attack. Common threats include malware (viruses, worms, trojans, ransomware), phishing (fraudulent emails that steal information) and brute-force password attacks. Defences include firewalls (filter network traffic), antivirus software, strong passwords and encryption. Encryption scrambles data so only someone with the correct key can read it — useful for protecting data both in transit and at rest.",
    defaultTimeLimit: 30,
    questions: [
      { question: "What does LAN stand for?", options: ["Local Area Network", "Large Access Node", "Long Array Network", "Local Application Net"], answer: 0, explanation: "LAN = Local Area Network — covers a small area such as a school or office.", timeLimit: 20 },
      { question: "What does an IP address do?", options: ["Stores files", "Uniquely identifies a device on a network", "Encrypts data", "Runs software"], answer: 1, explanation: "An IP address is a unique identifier for a device on a network.", timeLimit: 25 },
      { question: "What does DNS translate a domain name into?", type: "written", options: [], answer: 0, acceptAnswers: ["IP address", "an IP address", "ip address"], explanation: "DNS (Domain Name System) converts domain names like google.com into IP addresses.", timeLimit: 25 },
      { question: "Which protocol is used to securely transfer web pages?", options: ["FTP", "SMTP", "HTTPS", "POP3"], answer: 2, explanation: "HTTPS (Hypertext Transfer Protocol Secure) encrypts web traffic for security.", timeLimit: 25 },
      pp({ question: "Which is a type of malware?", options: ["Firewall", "Ransomware", "Router", "Browser"], answer: 1, explanation: "Ransomware is malware that locks or encrypts files until a ransom is paid.", timeLimit: 25 }),
      pp({ question: "A firewall is used to...", options: ["speed up the internet", "filter and block unauthorised network traffic", "store passwords", "create backups"], answer: 1, explanation: "A firewall inspects incoming/outgoing traffic and blocks unauthorised access.", timeLimit: 30 }),
      pp({ question: "Phishing is an attack that...", options: ["damages hardware", "uses fraudulent messages to steal sensitive information", "overloads a server with traffic", "encrypts files automatically"], answer: 1, explanation: "Phishing tricks users into revealing passwords or bank details via fake emails/websites.", timeLimit: 30 }),
      { question: "Encryption is used to...", options: ["compress files", "scramble data so only someone with the key can read it", "delete data permanently", "speed up a network"], answer: 1, explanation: "Encryption converts data into a form readable only with the correct decryption key.", timeLimit: 25 },
      { question: "On a network, data is sent in...", type: "written", options: [], answer: 0, acceptAnswers: ["packets", "packet"], explanation: "Data is broken into packets, each carrying the destination address, then reassembled at the receiver.", timeLimit: 25 },
      { question: "Which is the best defence against brute-force password attacks?", options: ["Using 'password' as your password", "Using a long, complex password", "Sharing your password", "Writing it on a sticky note"], answer: 1, explanation: "A long, complex password (or a passphrase) is far harder to crack by brute force.", timeLimit: 25 },
    ],
  },
];

/* ===================== BUSINESS STUDIES (ELECTIVE) ===================== */
const IGCSE_BUSINESS_TOPICS: Topic[] = [
  {
    id: "ig-biz-basics",
    name: "Business Basics",
    icon: "Briefcase",
    description: "Types of business, objectives and stakeholders.",
    questions: [
      { question: "What is the main aim of most businesses?", options: ["To lose money", "To make a profit", "To pay taxes", "To close down"], answer: 1, explanation: "Most businesses aim to make profit." },
      { question: "Which is a private limited company (Ltd)?", options: ["Shares sold to the public", "Shares not sold to the public", "Owned by the government", "No shares at all"], answer: 1, explanation: "An Ltd does not sell shares to the public." },
      { question: "Who is a stakeholder in a business?", options: ["Only the owners", "Anyone affected by the business", "Only customers", "Only the government"], answer: 1, explanation: "Stakeholders include owners, workers, customers, suppliers, the community." },
      { question: "What does 'unlimited liability' mean?", options: ["The business can only lose a fixed amount", "Owners can lose personal assets to pay business debts", "No debt is ever owed", "Only shareholders lose money"], answer: 1, explanation: "Unlimited liability = owners are personally responsible for all debts." },
      pp({ question: "Which business type has shares sold on a stock exchange?", options: ["Sole trader", "Partnership", "Private limited company (Ltd)", "Public limited company (PLC)"], answer: 3, explanation: "A PLC sells shares to the public on a stock exchange." }),
      pp({ question: "Which is an advantage of being a sole trader?", options: ["Easy to set up and keep all profit", "Limited liability", "Lots of capital", "Shares sold publicly"], answer: 0, explanation: "Sole traders are easy to set up and keep all profit — but have unlimited liability." }),
      pp({ question: "Revenue = ?", options: ["Price × quantity sold", "Costs − profit", "Price − cost", "Profit + tax"], answer: 0, explanation: "Revenue = price × quantity sold." }),
      pp({ question: "Profit = ?", options: ["Revenue + costs", "Revenue − costs", "Costs − revenue", "Price × quantity"], answer: 1, explanation: "Profit = revenue − total costs." }),
      pp({ question: "Which is a stakeholder concern about a new factory?", options: ["Share price only", "Pollution affecting local people", "Office stationery", "Weather"], answer: 1, explanation: "Local community stakeholders care about pollution and noise." }),
      pp({ question: "Which is an example of a not-for-profit organisation?", options: ["A supermarket", "A charity", "A PLC", "A bank"], answer: 1, explanation: "A charity is a not-for-profit organisation." }),
    ],
  },
  {
    id: "ig-biz-marketing",
    name: "Marketing",
    icon: "Briefcase",
    description: "The marketing mix (4Ps), market research, segmentation and advertising.",
    theory: "Marketing is about identifying, anticipating and satisfying customer needs profitably. The marketing mix is often called the 4 Ps: Product (what you sell, its features and design), Price (how much customers pay — strategies include penetration, skimming and competitive pricing), Place (how the product reaches the customer — distribution channels) and Promotion (how customers find out about the product — advertising, sales promotions, sponsorship, social media).\nMarket research gathers information about customers and competitors. Primary research collects new data first-hand (surveys, interviews, focus groups, observation); secondary research uses existing data (market reports, government statistics, internet research). Quantitative data is numerical; qualitative data is descriptive (opinions and feelings).\nMarket segmentation divides customers into groups with similar needs — by age, gender, income, location or lifestyle. This lets a business target its marketing more effectively. Advertising raises awareness and persuades customers; good advertising is targeted at the right segment through the right media channel.",
    defaultTimeLimit: 30,
    questions: [
      { question: "What are the 4 Ps of the marketing mix?", options: ["Product, Price, Place, Promotion", "Profit, People, Plan, Process", "Product, Profit, Place, People", "Price, Product, People, Power"], answer: 0, explanation: "The 4 Ps are Product, Price, Place and Promotion.", timeLimit: 25 },
      { question: "Which 'P' refers to how a product reaches the customer?", options: ["Product", "Price", "Place", "Promotion"], answer: 2, explanation: "Place covers distribution — the channels that get the product to the customer.", timeLimit: 25 },
      { question: "What type of market research collects data first-hand (e.g. surveys, interviews)?", type: "written", options: [], answer: 0, acceptAnswers: ["primary", "primary research"], explanation: "Primary research gathers new data directly (surveys, interviews, focus groups, observation).", timeLimit: 25 },
      { question: "Market segmentation means...", options: ["Selling only one product", "Dividing customers into groups with similar needs", "Charging everyone the same price", "Ignoring competitors"], answer: 1, explanation: "Segmentation splits the market into groups (by age, income, location, lifestyle) to target them effectively.", timeLimit: 30 },
      pp({ question: "Penetration pricing means...", options: ["setting a high price to maximise profit", "setting a low price to gain market share quickly", "charging different prices by region", "copying a rival's price"], answer: 1, explanation: "Penetration pricing uses a low initial price to attract customers and build market share.", timeLimit: 30 }),
      pp({ question: "Which is an example of secondary market research?", options: ["A survey you conduct", "A focus group you run", "A published industry market report", "Observing shoppers in a store"], answer: 2, explanation: "Secondary research uses existing data, such as published market reports or government statistics.", timeLimit: 30 }),
      pp({ question: "Qualitative market research data is...", options: ["numerical and statistical", "descriptive (opinions and feelings)", "always from the internet", "unreliable"], answer: 1, explanation: "Qualitative data is descriptive — opinions, feelings and reasons — rather than numerical.", timeLimit: 30 }),
      { question: "Which is an example of sales promotion?", options: ["A TV advert", "A 'buy one get one free' offer", "Sponsoring a football team", "Designing a new logo"], answer: 1, explanation: "BOGOF and discounts are sales promotions — short-term incentives to boost sales.", timeLimit: 25 },
      { question: "Skimming pricing means setting a ___ price for a new, innovative product, then lowering it later.", type: "written", options: [], answer: 0, acceptAnswers: ["high", "high price"], explanation: "Price skimming sets a high initial price (targeting early adopters), then reduces it over time.", timeLimit: 30 },
      { question: "Which promotion method uses paid media to reach a wide audience and build awareness?", options: ["Advertising", "Word of mouth only", "After-sales service", "Distribution"], answer: 0, explanation: "Advertising uses paid media (TV, online, print, billboards) to reach a wide audience and raise awareness.", timeLimit: 25 },
    ],
  },
];

export const IGCSE_SUBJECTS: IgcseSubjectInfo[] = [
  { id: "maths_core", name: "Mathematics (Core)", icon: "Sigma", color: "#a855f7", core: true, description: "Core mathematics: number, algebra, geometry and statistics.", topics: IGCSE_MATHS_TOPICS },
  { id: "maths_extended", name: "Mathematics (Extended)", icon: "Sigma", color: "#c084fc", core: false, description: "Extended mathematics with harder algebra, calculus basics and advanced topics.", topics: IGCSE_MATHS_TOPICS },
  { id: "english", name: "English", icon: "BookOpen", color: "#f472b6", core: true, description: "Language and literature — grammar, comprehension and writing.", topics: IGCSE_ENGLISH_TOPICS },
  { id: "physics", name: "Physics", icon: "Zap", color: "#22d3ee", core: false, description: "Forces, energy, electricity and waves.", topics: IGCSE_PHYSICS_TOPICS },
  { id: "chemistry", name: "Chemistry", icon: "FlaskConical", color: "#34d399", core: false, description: "Atomic structure, reactions and the Periodic Table.", topics: IGCSE_CHEMISTRY_TOPICS },
  { id: "biology", name: "Biology", icon: "Leaf", color: "#84cc16", core: false, description: "Cells, organisms and ecosystems.", topics: IGCSE_BIOLOGY_TOPICS },
  { id: "economics", name: "Economics", icon: "TrendingUp", color: "#facc15", core: false, description: "Scarcity, markets and the economic problem.", topics: IGCSE_ECONOMICS_TOPICS },
  { id: "ict", name: "ICT", icon: "Cpu", color: "#60a5fa", core: false, description: "Hardware, software, networks and data.", topics: IGCSE_ICT_TOPICS },
  { id: "business", name: "Business Studies", icon: "Briefcase", color: "#fb923c", core: false, description: "Types of business, objectives and stakeholders.", topics: IGCSE_BUSINESS_TOPICS },
];

export function getIgcseSubject(id: IgcseSubjectId): IgcseSubjectInfo | undefined {
  return IGCSE_SUBJECTS.find((s) => s.id === id);
}
